dwcaress/MB-System

- libtool
- src/mbgrdviz/Makefile.am
- src/mbgrdviz/mbgrdviz_callbacks.c
Backed off use of libuuid in mbgrdviz_callbacks
> 5.6.20181129.b

- .travis.yml
- travis/install-post.sh
- travis/install-ubuntu.sh
- travis/script.sh
This is purely a build setup at this point.  There are no tests yet.
Based loosely on [ValveSoftware/GameNetworkingSockets/.travis.yml](https://github.com/ValveSoftware/GameNetworkingSockets/blob/363b6869cf7d125330b3fc1ebc271ab7124644e4/.travis.yml)
Closes #8
> Initial Travis-CI config using Docker with Ubuntu 19.04 Disco Dingo for continuous integration.

- src/mbio/mbf_hsatlraw.h
- src/mbio/mbr_hsatlraw.c
Preparing to test format 21 - hydrosweep raw.
Also cleanup includes a bit.
> hsatlraw: Move prototypes to header for testing.

- src/mbio/mb_absorption.c
- src/mbio/mb_access.c
- src/mbio/mb_buffer.c
- src/mbio/mb_check_info.c
- src/mbio/mb_esf.c
- src/mbio/mb_mem.c
- src/mbio/mb_navint.c
- src/mbio/mb_platform.c
- src/mbio/mb_process.c
- src/mbio/mb_put_all.c
- src/mbio/mb_rt.c
- src/mbio/mb_segy.c
- src/mbio/mb_spline.c
Found with:
```bash
cppcheck --enable=style --std=c99 --force mb_*.c 2>&1 | egrep "'[ijkl]'"
```
> mbio/mb_*.c: Localize loop many of the counters

- src/mbio/mb_rt.c
- src/mbio/mb_spline.c
> MBBA -> MBIO

- src/mbio/mbr_hsatlraw.c
- src/mbio/mbr_mgd77txt.c
- src/utilities/mbinfo.c
See also:
https://twitter.com/kurtschwehr/status/1124294030374780929
https://godbolt.org/z/wJ8iut
https://stackoverflow.com/questions/7959573/declaring-variables-inside-loops-good-practice-or-bad-practice
> Localize for loop counter i  where there is test coverage.

- test/utilities/Makefile.am
- test/utilities/Makefile.in
- test/utilities/mbconfig_test.py
Marked questionable / incorrect behavior with TODO.
Also add all possible targets to src/utilities/Makefile.am, but commented out.
> Add mbconfig_test.py.

- src/mbio/mbr_mgd77txt.c
Also:
- Combine definition and initialization when possible
- Order includes
> mbr_mgd77txt.c: Localize variables

- test/utilities/Makefile.am
- test/utilities/Makefile.in
This should have been a part of #122 /
https://github.com/dwcaress/MB-System/pull/122/commits/29a4ea65f25f7bd4ed908227605e8aa85ae8d28d
> Enable mbabsorption_test.py

- src/utilities/mb7k2jstar.c
- test/utilities/Makefile.am
- test/utilities/Makefile.in
- test/utilities/mb7k2jstar_test.py
Also initialize IO string args so that dbg2 output is valid.
> Introduce utilities/mb7k2jstar_test.py.

- src/utilities/mbclean.c
- test/utilities/Makefile.am
- test/utilities/Makefile.in
- test/utilities/mbbackangle_test.py
- test/utilities/mbclean_test.py
- test/utilities/mbcopy_test.py
- test/utilities/mbctdlist_test.py
- test/utilities/mbdatalist_test.py
Also remove extra spaces in usage of mbclean.c.
> Introduce test/utilities/ mbbackangle_test.py mbclean_test.py mbctdlist_test.py mbdatalist_test.py.

- src/mbaux/mb_aux.h
- src/mbaux/mb_xgraphics.h
https://mbari1.atlassian.net/browse/MBSYS-12
> Add include guards to mbaux.

- src/mbaux/mb_track.c
- Remove unused defines
- Add const
- Comment out unused code for x2, y2
- printf %d -> %u for an unsigned int
> mb_track.c: cleanup

- src/mbaux/mb_truecont.c
> mb_truecont.c: clean

- src/mbio/mb_buffer.c
> mb_buffer.c: Cleanup

- src/mbio/mb_check_info.c
- Comment out unchecked vars (e.g. shellstatus)
- Add TODOs to check results of system calls
> mb_check_info.c: Cleanup

- src/mbio/mb_close.c
- status = -> status &= to catch error conditions that were being hidden
> mb_close.c: Cleanup

- src/mbio/mb_coor_scale.c
> mb_coor_scale.c: Cleanup

- src/mbio/mb_get_all.c
- Pass along failures by doing `status &=`
> mb_get_all.c: cleanup

- src/mbio/mb_get_value.c
> mb_get_value.c: Cleanup

- src/mbio/mbr_3ddepthp.c
- src/mbio/mbr_3dwisslp.c
- src/mbio/mbr_3dwisslr.c
- src/mbio/mbr_asciixyz.c
- src/mbio/mbr_bchrtunb.c
- src/mbio/mbr_bchrxunb.c
- src/mbio/mbr_cbat8101.c
- src/mbio/mbr_cbat9001.c
- src/mbio/mbr_dsl120pf.c
- src/mbio/mbr_dsl120sf.c
- src/mbio/mbr_edgjstar.c
- src/mbio/mbr_elmk2unb.c
Partial - only an initial start
> mbr*.c: Move register to the end of each file and remove unnecessary prototypes.

- src/mbio/mbr_3dwisslp.c
- Add TODO for file_header_readwritten immediately overwritten
> mbr_3dwisslp.c: Cleanup

- src/mbio/mbr_kemkmall.c
- src/mbio/mbr_swplssxp.c
- src/mbio/mbr_wasspenl.c
- src/mbio/mbr_xtfb1624.c
- src/mbio/mbr_xtfr8101.c
mbr_kemkmall.c mbr_swplssxp.c mbr_wasspenl.c mbr_xtfb1624.c mbr_xtfr8101.c
> Reorg to not need local prototypes.

- src/mbio/mbr_mbpronav.c
- src/mbio/mbr_reson7k3.c
- src/mbio/mbr_reson7kr.c
- src/mbio/mbr_sb2100bi.c
- src/mbio/mbr_sb2100rw.c
- src/mbio/mbr_sbifremr.c
- src/mbio/mbr_swplssxp.c
- src/mbio/mbr_tempform.c
mbr_mbpronav.c mbr_reson7k3.c mbr_reson7kr.c mbr_sb2100bi.c
mbr_sb2100rw.c mbr_sbifremr.c mbr_swplssxp.c mbr_tempform.c
> Reorg to not need local prototypes. Final one for mbr_*.c

- src/mbio/mb_esf.c
Only partially done.  There are some tricky macros to work through.
> mb_esf.c: Localize vars

- src/mbtrn/cbuffer.c
- src/mbtrn/fsync.c
- src/mbtrn/iowrap-posix.c
- src/mbtrn/iowrap-posix.h
- src/mbtrn/mbtrn-server.c
- src/mbtrn/mbtrn.c
- src/mbtrn/mlog.c
- src/mbtrn/r7kc.c
- src/mbtrn/strptime.c
- src/mbtrn/windirent.h
Here I had to find also replacements for the ``fsync`` and `strptime`` programs that do not exist in MSVC
> Changes to let it compile with VisualStudio

- src/mbio/mb_get.c
- Localize vars (partial)
- `status` = -> `status &=`
- Add `const`
This fixes all cppcheck warnings of merit.
```
cppcheck --enable=all --std=c99 --force mb_get.c
Checking mb_get.c ...
Checking mb_get.c: DEFINE_MB_MESSAGES...
Checking mb_get.c: HAVE_CONFIG_H...
Checking mb_get.c: HAVE_RPC_RPC_H...
Checking mb_get.c: HAVE_RPC_TYPES_H...
Checking mb_get.c: HAVE_STDINT_H...
Checking mb_get.c: INT8_MAX;int8_t...
[mb_define.h:97]: (information) Skipping configuration 'INT8_MAX;int8_t' since the value of 'int8_t' is unknown. Use -D if you want to check it. You can use -U to skip it explicitly.
Checking mb_get.c: MBTRN_ENABLED...
Checking mb_get.c: NO_IEEE...
Checking mb_get.c: _WIN32...
Checking mb_get.c: _WIN32;copysign...
Checking mb_get.c: _WIN32;inline...
Checking mb_get.c: _WIN32;isnan... …
```
> mb_get.c: Cleanup

- src/mbio/mb_read_init.c
status_save and error_save do not appear to actually do anything.
The error handling needs to be generally reevaluated.
> mb_read_init.c: Localize vars

- src/mbio/mbr_3dwisslr.c
- src/mbio/mbr_asciixyz.c
- src/mbio/mbr_bchrtunb.c
- src/mbio/mbr_bchrxunb.c
- src/mbio/mbr_cbat8101.c
- src/mbio/mbr_cbat9001.c
- src/mbio/mbr_dsl120pf.c
- src/mbio/mbr_dsl120sf.c
- src/mbio/mbr_edgjstar.c
- src/mbio/mbr_elmk2unb.c
- src/mbio/mbr_em12darw.c
- src/mbio/mbr_em12ifrm.c
- src/mbio/mbr_mbarrov2.c
egrep '^[   ]+(data|store) = ' *.c
mbr_3dwisslr.c mbr_asciixyz.c mbr_bchrtunb.c mbr_bchrxunb.c
mbr_cbat8101.c mbr_cbat9001.c mbr_dsl120pf.c mbr_dsl120sf.c
mbr_edgjstar.c mbr_elmk2unb.c mbr_em12darw.c mbr_em12ifrm.c
mbr_mbarrov2.c
> Localize data and store variables (partial)

- src/mbio/mbr_em300mba.c
- src/mbio/mbr_em300raw.c
- src/mbio/mbr_em710mba.c
- src/mbio/mbr_em710raw.c
- src/mbio/mbr_emoldraw.c
- src/mbio/mbr_hsatlraw.c
- src/mbio/mbr_hsds2lam.c
- src/mbio/mbr_hsds2raw.c
- src/mbio/mbr_hsldeoih.c
- src/mbio/mbr_hsmdaraw.c
- src/mbio/mbr_hsmdldih.c
- src/mbio/mbr_hypc8101.c
- src/mbio/mbr_hysweep1.c
mbr_em300mba.c mbr_em300raw.c mbr_em710mba.c mbr_em710raw.c
mbr_emoldraw.c mbr_hsatlraw.c mbr_hsds2lam.c mbr_hsds2raw.c
mbr_hsldeoih.c mbr_hsmdaraw.c mbr_hsmdldih.c mbr_hypc8101.c
mbr_hysweep1.c
> Localize data and store variables (partial part 2).

- src/mbio/mbr_image83p.c
- src/mbio/mbr_imagemba.c
- src/mbio/mbr_kemkmall.c
- src/mbio/mbr_l3xseraw.c
mbr_image83p.c mbr_imagemba.c mbr_kemkmall.c mbr_l3xseraw.c
> Localize variables.

- src/mbio/mbr_mbarrov2.c
- src/mbio/mbr_mbldeoih.c
- src/mbio/mbr_mbnetcdf.c
- src/mbio/mbr_mgd77dat.c
- src/mbio/mbr_mr1aldeo.c
- src/mbio/mbr_mr1bldeo.c
- src/mbio/mbr_mr1prhig.c
- src/mbio/mbr_mr1prvr2.c
- src/mbio/mbr_mstiffss.c
- src/mbio/mbr_nvnetcdf.c
- src/mbio/mbr_oicgeoda.c
- src/mbio/mbr_oicmbari.c
- src/mbio/mbr_omghdcsj.c
- src/mbio/mbr_photgram.c
mbr_mbarrov2.c mbr_mbldeoih.c mbr_mbnetcdf.c mbr_mgd77dat.c
mbr_mr1aldeo.c mbr_mr1bldeo.c mbr_mr1prhig.c mbr_mr1prvr2.c
mbr_mstiffss.c mbr_nvnetcdf.c mbr_oicgeoda.c mbr_oicmbari.c
mbr_omghdcsj.c mbr_photgram.c
> Localize variables. (#279)

- src/mbio/mbr_reson7k3.c
- src/mbio/mbr_samesurf.c
- src/mbio/mbr_sb2000sb.c
- src/mbio/mbr_sb2000ss.c
- src/mbio/mbr_sb2100bi.c
- src/mbio/mbr_sb2100rw.c
- src/mbio/mbr_sbsioswb.c
- src/mbio/mbr_tempform.c
- src/mbio/mbr_wasspenl.c
- src/mbio/mbsys_xse.c
mbr_samesurf.c mbr_sb2000sb.c mbr_sb2000ss.c mbr_sb2100bi.c
mbr_sb2100rw.c mbr_sbsioswb.c mbr_tempform.c mbr_wasspenl.c
mbsys_xse.c
> Localize data and store variables.

- src/mbio/mbsys_mr1v2001.c
- src/mbio/mbsys_navnetcdf.c
- src/mbio/mbsys_reson7k3.c
Also remove quite a few unused variables from mbsys_reson7k3.c
> Localize variables: mbsys_mr1v2001.c mbsys_navnetcdf.c mbsys_reson7k3.c

- src/utilities/mbinfo.c
- Create an `enum OutputFormat`
- Convert some strings to `static const char []`
- Localize a few variables
- `status =` -> `status &=` to catch more failures
- Add `{}` for case JSON
> mbinfo.c: Cleanup

- src/utilities/mbnavlist.c
- Remove unused `printNaN` function
- Move `printsimplevalue` to avoid needing an extra prototype
- `char[]` -> `static const char[]`
- Remove unnecessary `extern char *optarg;`
- Define one variable per line
> mbnavlist.c: Cleanup

- src/mbaux/mb_readwritegrd.c
> mb_readwritegrd.c: Cleanup

- src/gmt/Makefile.am
- Remove unused trn stuff
- Convert line continuations to +=
- Sort sources
> gmt/Makefile.am: Cleanup

- Makefile.am
- src/mbedit/Makefile.am
- src/mbeditviz/Makefile.am
- src/mbgrdviz/Makefile.am
- src/mbio/Makefile.am
- src/mbnavadjust/Makefile.am
- src/mbnavedit/Makefile.am
- src/mbtrn/Makefile.am
- src/mbvelocitytool/Makefile.am
- src/mbview/Makefile.am
- src/otps/Makefile.am
- src/utilities/Makefile.am
- Convert line continuations to +=
- Sort sources
- Whitespace cleanup
- Remove unused references to TRN
> Cleanup Makefile.am files

- src/mbaux/mb_surface.c
Also remove some unused functions
> mb_surface.c: Reorder functions to remove the need for prototypes

- src/bsio/bs.3
- src/bsio/mbbs_iomrv1.c
- src/bsio/mbbs_iomrv2.c
- src/bsio/mbbs_memalloc.c
- src/bsio/mbbs_swapbytes.c
- src/bsio/mbbs_wrsampflags.c
- Fix whitespace
- Remove unnecessary externs
- Reorder to need fewer prototypes
- Add const
> mbbs general cleanup

- src/bsio/mbbs.h
- src/bsio/mbbs_wrsampflags.c
- Move mbbs_xdrpnghdr prototype to mbbs.h
- Remove local prototypes
- Add const
> mbbs_wrsampflags.c: Cleanup

- src/mbio/mbr_omghdcsj.c
- Initial work on cppcheck comments
- Comment out unused profile
- Add const
Lots more todo
> mbr_omghdcsj.c: Clean

- src/bsio/mbbs_utils.c
- Flag for removal.  mbbs_splitfile is unused
- Remove unnecessary local prototypes
- Add include of mbbs.h
> mbbs_utils.c: Cleanup

- src/bsio/mbbs_misc.c
- Add mbbs.h include
- Always include float.c
- sort includes
- Put function comments before function
- Localize varialbes
- Remove unnecessary function prototype of mbbs_pngdatabufsz()
- Add const
- Drop SOLARIS and IRIX cases for isnanf / isnand
> mbbs_misc.c: Cleanup

- src/utilities/mb7k2jstar.c
- Most cppcheck complaints
- Most -Wall and -Wextra warnings
- Localize some variables
- Add a scope around option parsing and one around case b
- = -> &= for stats
- Remove some unused code
- Do not print "file" as it has not yet been set
- Add const
> mb7k2jstar.c: Cleanup

- src/mbio/mb_absorption.c
- Remove non-essential comments
- Add const
- Remove unused result variable
> mb_absorption.c: Clenaup

- src/utilities/mbmakeplatform.c
- Make string constants be static const
- Remove large redudant comment about the command line args
- Remove unused input_platform_file_defined
> mbmakeplatform.c: Cleanup

- src/mbio/mb_access.c
- Add const to some status vars
- Remove useless error tracking code
> mb_access.c: Cleanup

- src/utilities/mbareaclean.c
- #define -> static const int
- char strings -> static const char []
- Localize some variables
- Comment out unused beams_file variable
> mbareaclean.c: Cleanup

- src/utilities/mbauvloglist.c
- Add const
- Remove unused interp_status
- Remove redundant return at the end of void function
> mbauvloglist.c: Partial cleanup

- src/utilities/mbauvnavusbl.c
- Make string constants static const
- Comment out unused intstat
> mbauvnavusbl.c: Cleanup

- travis/script.sh
Holding off on -Wextra until the noise decreases a bit
> travis: Up compiler warnings with -Wall

- src/mbio/mb_define.h
- src/mbio/mb_spline.c
Input only pointer args should be const.
> mb_spline.c: Make first 2 args const and cleanup the includes.

- src/utilities/mb7k2ss.c
- Move mb7k2ss_get_flatbottom_table to the top to avoid need for a prototype
- Add const
> mb7k2ss.c: Cleanup

- src/utilities/mb7kpreprocess.c
> mb7kpreprocess.c: Cleanup

- src/utilities/mbbackangle.c
- test/utilities/mbbackangle_test.py
- Start using stdbool.h
- Add const
- Make a new scope for getopt
> mbbackangle.c: Cleanup

- src/utilities/mbcopy.c
> mbcopy.c: Cleanup

- src/utilities/mb7k2ss.c
- src/utilities/mb7kpreprocess.c
- src/utilities/mbareaclean.c
- src/utilities/mbbackangle.c
- src/utilities/mbclean.c
- src/utilities/mbdefaults.c
- src/utilities/mbfilter.c
- src/utilities/mbgrid.c
- src/utilities/mblist.c
- src/utilities/mbmosaic.c
- src/utilities/mbnavlist.c
- src/utilities/mbneptune2esf.c
- src/utilities/mbpreprocess.c
- src/utilities/mbprocess.c
- src/utilities/mbps.c
- src/utilities/mbrollbias.c
- src/utilities/mbrolltimelag.c
- src/utilities/mbsegygrid.c
2nd try of #440 without the foo/*.c I accidentally added.
> utilities: Localize i-n ints.

- src/utilities/mbtime.c
- errflag and flag to stdbool.h types
- Remove unused flag variable
- Convert defines to an enum
> mbtime.c - Cleanup

- src/utilities/mbabsorption.c
- Use stdbool for help and errflag
- Remove unused flag variable
- Add const
- Add a scope for getopt
- `status =` -> `status &=`
> mbabsorption.c: Cleanup

- src/utilities/mbconfig.c
- Use `stdbool.h`
- Create a scope for `getopt_long`
- Call `mb_version()` after parsing args
- Do not test `== true` or `== false`.  The later is !flag
> mbconfig.c: Cleanup

- src/utilities/mblevitus.c
- Use stdbool
- Move includes to one section near the top of the file
- Move depth values to a global static const array
- Add const
- Call exit with the error code rather than via setting error
- Add scopes for getopt and for date, user, and host
- Move `GMT_runtime_bindir_win32()` to near the top to avoid needing a prototype
> mblevitus.c: Cleanup

- README.md
Make the README file in markdown.
> Make README.md

- src/utilities/mb7k2jstar.c
- src/utilities/mb7k2ss.c
- src/utilities/mb7kpreprocess.c
- src/utilities/mbareaclean.c
- src/utilities/mbauvloglist.c
- src/utilities/mbauvnavusbl.c
- src/utilities/mbgetesf.c
mb7k2jstar.c mb7k2ss.c mb7kpreprocess.c mbareaclean.c
mbauvloglist.c mbauvnavusbl.c mbgetesf.c
> utilities: Create scope for getopt.

- src/utilities/mbmakeplatform.c
- src/utilities/mbmosaic.c
- src/utilities/mbnavlist.c
- src/utilities/mbneptune2esf.c
- src/utilities/mbpreprocess.c
mbmakeplatform.c mbmosaic.c mbnavlist.c mbneptune2esf.c mbpreprocess.c
> utilities: Convert error = FOO; exit(error); -> exit(FOO);

- src/utilities/mb7k2jstar.c
- Convert read_datalist to a const bool
- Convert new_output_file to a bool
> mb7k2jstar.c: Cleanup (partial)

- src/utilities/mb7k2ss.c
Also remove commented out fprintf calls
> mb7k2ss.c: int boolean -> bool and localize those variables

- src/utilities/mb7k2ss.c
- src/utilities/mbareaclean.c
- src/utilities/mbbackangle.c
- src/utilities/mbcopy.c
- src/utilities/mbdatalist.c
- src/utilities/mbextractsegy.c
- src/utilities/mbfilter.c
- src/utilities/mbgetesf.c
- src/utilities/mbgrid.c
- src/utilities/mbhysweeppreprocess.c
- src/utilities/mbinsreprocess.c
- src/utilities/mbkongsbergpreprocess.c
- src/utilities/mbmakeplatform.c
- src/utilities/mbmosaic.c
- src/utilities/mbpreprocess.c
- src/utilities/mbprocess.c
- src/utilities/mbsegygrid.c
- src/utilities/mbsegyinfo.c
- src/utilities/mbsegylist.c
- src/utilities/mbsegypsd.c
- src/utilities/mbsslayout.c
- src/utilities/mbtrnpreprocess.c
- src/utilities/mbvoxelclean.c
Mostly found with:
```egrep --color -nH --null -e '[/]?[*/] ?fprintf' *.c```
Anything that was removed here that really is critical should be
converted to a logging style message.  And MB-System really should
adopt a logging system.
> utilities: Remove commented out code.

- src/utilities/mb7kpreprocess.c
- src/utilities/mbclean.c
egrep --color -nH --null -e '[/]?[*/] ?fprintf' *.c
> mb7kpreprocess.c and mbclean.c: Remove commented out code.

- src/utilities/mb7kpreprocess.c
- src/utilities/mbareaclean.c
- src/utilities/mbbackangle.c
- src/utilities/mbclean.c
- src/utilities/mbctdlist.c
- src/utilities/mbextractsegy.c
- src/utilities/mbfilter.c
- src/utilities/mbgpstide.c
- src/utilities/mbhistogram.c
- src/utilities/mbhysweeppreprocess.c
- src/utilities/mbinfo.c
- src/utilities/mbkongsbergpreprocess.c
- src/utilities/mblist.c
- src/utilities/mbnavlist.c
- src/utilities/mbneptune2esf.c
- src/utilities/mbpreprocess.c
- src/utilities/mbprocess.c
- src/utilities/mbrolltimelag.c
- src/utilities/mbroutetime.c
- src/utilities/mbrphsbias.c
- src/utilities/mbset.c
- src/utilities/mbsslayout.c
- src/utilities/mbsvplist.c
- src/utilities/mbswplspreprocess.c
- src/utilities/mbtrnpreprocess.c
- src/utilities/mbvoxelclean.c
```
read_datalist == MB_NO  -> !read_datalist
read_datalist == MB_YES ->  read_datalist
```
Part 1: https://github.com/dwcaress/MB-System/commit/40b6c4b8637f8914ca00e9d4b75d18cbd5c2fd7a
> utilities: read_datalist == (MB_NO|MB_YES) cleanup part 2.

- src/mbio/mb_esf.c
- src/mbio/mb_format.c
- src/mbio/mb_navint.c
- src/mbio/mb_process.c
- src/mbio/mbr_em300mba.c
mb_esf.c mb_format.c mb_navint.c mb_process.c mbr_em300mba.c
> mbio: Start fixing -Wunused-but-set-variable complaints

- src/mbio/mb_get_value.c
egrep 'MB_(YES|NO) +[0-9]' *.h
mb_status.h:#define MB_YES 1
mb_status.h:#define MB_NO 0
> mb_get_value.c: Use MB_NO and MB_YES can be directly as bools.

- src/mbio/mb_define.h
- src/mbio/mb_get_value.c
Also make the input pointer be const.
> mb_get_value.c: Convert int boolean swapped arg to bool for mb_get_binary_*().

- src/utilities/mb7kpreprocess.c
- src/utilities/mbauvnavusbl.c
- src/utilities/mbbackangle.c
mb7kpreprocess.c mbauvnavusbl.c mbbackangle.c
Found with:
```bash
egrep -nH "[   ]int .* (true|false)" *.c
```
> utilities: Convert int boolean -> bool

- src/utilities/mbextractsegy.c
- src/utilities/mbfilter.c
- src/utilities/mbgetesf.c
- src/utilities/mbgpstide.c
mbextractsegy.c mbfilter.c mbgetesf.c mbgpstide.c
> utilities: Convert int boolean → bool

- src/mbio/mb_buffer.c
- src/mbio/mb_check_info.c
- src/mbio/mb_esf.c
- src/mbio/mb_format.c
- src/mbio/mb_mem.c
- src/mbio/mb_process.c
- src/mbio/mbr_3dwisslp.c
- src/mbio/mbr_3dwisslr.c
- src/mbio/mbr_em300mba.c
- src/mbio/mbr_em300raw.c
- src/mbio/mbr_em710mba.c
- src/mbio/mbr_em710raw.c
- src/mbio/mbr_hsatlraw.c
- src/mbio/mbr_image83p.c
- src/mbio/mbr_imagemba.c
- src/mbio/mbr_l3xseraw.c
- src/mbio/mbr_mbnetcdf.c
- src/mbio/mbr_photgram.c
- src/mbio/mbr_reson7k3.c
- src/mbio/mbr_sb2000ss.c
- src/mbio/mbr_sb2100rw.c
- src/mbio/mbr_sbifremr.c
- src/mbio/mbr_xtfb1624.c
- src/mbio/mbsys_atlas.c
- src/mbio/mbsys_gsf.c
- src/mbio/mbsys_hysweep.c
- src/mbio/mbsys_image83p.c
- src/mbio/mbsys_mr1v2001.c
- src/mbio/mbsys_reson7k.c
- src/mbio/mbsys_reson7k3.c
mb_buffer.c mb_check_info.c mb_esf.c mb_format.c mb_mem.c mb_process.c
mbr_3dwisslp.c mbr_3dwisslr.c mbr_em300mba.c mbr_em300raw.c
mbr_em710mba.c mbr_em710raw.c mbr_hsatlraw.c mbr_image83p.c
mbr_imagemba.c mbr_l3xseraw.c mbr_mbnetcdf.c mbr_photgram.c
mbr_reson7k3.c mbr_sb2000ss.c mbr_sb2100rw.c mbr_sbifremr.c
mbr_xtfb1624.c mbsys_atlas.c mbsys_gsf.c mbsys_hysweep.c
mbsys_image83p.c mbsys_mr1v2001.c mbsys_reson7k.c mbsys_reson7k3.c
> mbio: Convert int boolean -> bool

- src/mbio/mb_io.h
- src/mbio/mbsys_hysweep.h
- src/mbio/mbsys_reson7k.h
- src/mbio/mbsys_reson7k3.h
- src/mbio/mbsys_simrad3.h
mb_io.h mbsys_hysweep.h mbsys_reson7k.h mbsys_reson7k3.h mbsys_simrad3.h
> mbio headers: int boolean -> bool and some TODO for the same

- src/utilities/mbvoxelclean.c
- Fix some formatting
- #define → const int
- Make usage_message more readable
- Add const
- Remove unused file pointer
> mbvoxelclean.c: Cleanup

- src/mbio/mb_buffer.c
- src/mbio/mb_check_info.c
- src/mbio/mb_esf.c
- src/mbio/mb_get.c
- src/mbio/mb_mem.c
- src/mbio/mb_navint.c
- src/mbio/mb_process.h
- src/mbio/mb_time.c
mb_buffer.c mb_check_info.c mb_esf.c mb_get.c mb_mem.c mb_navint.c
Minor cleanup: mb_time.c
> mbio: Convert int boolean → bool

- src/mbio/mb_process.c
- Remove redundant else setting that sets to the original value
- Add const
> mb_process.c: Cleanup

- src/utilities/mbareaclean.c
- src/utilities/mbauvloglist.c
- src/utilities/mbclean.c
- src/utilities/mbgetesf.c
- src/utilities/mbgrid.c
- src/utilities/mbhsdump.c
- src/utilities/mbmosaic.c
- src/utilities/mbneptune2esf.c
- src/utilities/mbprocess.c
- src/utilities/mbrphsbias.c
- src/utilities/mbsegygrid.c
- src/utilities/mbsegylist.c
- src/utilities/mbsegypsd.c
- src/utilities/mbset.c
- src/utilities/mbsslayout.c
- src/utilities/mbsvplist.c
- src/utilities/mbsvpselect.c
mbareaclean.c mbauvloglist.c mbclean.c mbgetesf.c mbgrid.c mbhsdump.c
mbmosaic.c mbneptune2esf.c mbprocess.c mbrphsbias.c mbsegygrid.c
mbsegylist.c mbsegypsd.c mbset.c mbsslayout.c mbsvplist.c mbsvpselect.c
- Localize char *message
- Convert #defines to const int
- Localize variables and combine initialization with definition
- Add const
- Remove unused variables
- int Is_Leap() -> bool Is_Leap()
> utilities: Cleanup

- src/mbio/mbsys_atlas.c
- src/mbio/mbsys_benthos.c
- src/mbio/mbsys_dsl.c
- src/mbio/mbsys_elac.c
- src/mbio/mbsys_elacmk2.c
mbsys_atlas.c mbsys_benthos.c mbsys_dsl.c mbsys_elac.c mbsys_elacmk2.c
- Remove extra comment lines / dead code
- Add const
> mbio: Cleanup

- src/utilities/mbroutetime.c
> mbroutetime.c: Cleanup

- src/utilities/mbclean.c
- src/utilities/mbcopy.c
- src/utilities/mbctdlist.c
- src/utilities/mbdefaults.c
- src/utilities/mbdumpesf.c
- src/utilities/mbextractsegy.c
- src/utilities/mbfilter.c
- src/utilities/mbgetesf.c
- src/utilities/mbgrid.c
mbclean.c mbcopy.c mbctdlist.c mbdefaults.c mbdumpesf.c
mbextractsegy.c mbfilter.c mbgetesf.c mbgrid.c
> utilities: convert #define to const int or const double

- src/mbio/mb_format.c
- src/mbio/mbr_em12ifrm.c
- src/mbio/mbsys_3ddwissl.c
- src/mbio/mbsys_benthos.c
- src/mbio/mbsys_dsl.c
- src/mbio/mbsys_kmbes.c
mb_format.c mbr_em12ifrm.c mbsys_3ddwissl.c mbsys_benthos.c
mbsys_dsl.c mbsys_kmbes.c
> mbio: Cleanup.

- src/utilities/mbhysweeppreprocess.c
- src/utilities/mbinsreprocess.c
- src/utilities/mbkongsbergpreprocess.c
- src/utilities/mblist.c
- src/utilities/mbmosaic.c
mbhysweeppreprocess.c mbinsreprocess.c mbkongsbergpreprocess.c
mblist.c mbmosaic.c
> utilities: convert more to enums

- src/utilities/mbgrid.c
- src/utilities/mbhistogram.c
> utilities: const int -> enum

- src/utilities/mbauvloglist.c
- src/utilities/mbbackangle.c
- src/utilities/mbclean.c
- src/utilities/mbcopy.c
- src/utilities/mbctdlist.c
mbauvloglist.c mbbackangle.c mbclean.c mbcopy.c mbctdlist.c
> utilities: Cleanup - mostly moving default to the front of main and localizing message

- src/utilities/mb7kpreprocess.c
- src/utilities/mbauvnavusbl.c
- src/utilities/mbfilter.c
- src/utilities/mbgpstide.c
- src/utilities/mbhistogram.c
- src/utilities/mbhysweeppreprocess.c
mb7kpreprocess.c mbauvnavusbl.c mbfilter.c mbgpstide.c mbhistogram.c
mbhysweeppreprocess.c
> utilities: Localize message.

- src/utilities/mbfilter.c
- Localize vars below option parsing
- Remove unused error arg from filter functions (-Wunused-parameter)
- Misc other
> mbfilter.c: Cleanup

- src/utilities/mbkongsbergpreprocess.c
- Comment out some unused variables
> mbkongsbergpreprocess.c: Cleanup

- src/utilities/mblist.c
- MAX_OPTIONS back to #define as it is the size of a char[]
- Remove accidental extra ;
- Cleanup initialization of strings
> mblist.c: Cleanup

- src/utilities/mbmosaic.c
- Convert const int to enums
- Localize a few variables
- Add const
> mbmosaic.c: Cleanup

- src/utilities/mbmosaic.c
Lots more that can still be done to reduce the scope of vars
> mbmosaic.c: More variable localization and adding const

- src/utilities/mbauvloglist.c
- Convert const int -> enum
- Add const
> mbauvloglist.c: Cleanup

- src/utilities/mbclean.c
- Make y_mode_t enum from MBCLEAN_Y_MODE*
- Move mbclean_save_edit to the top to remove need for prototype
- Remove unused variables: lock_status, find_bad, last_heading, last_time, start, distance_right, n, p, b
- Fix setting of errflg bool
> mbclean.c: Cleanup

- src/utilities/mbsslayout.c
- Line up newlines in help_message
- Define one variable per line
- Comment out unused variables.  especially n
- Set max string size for sscanf
- Add const
- Comment out unused status =
- combine two adjacent if (verbose > 0) blocks
> mbsslayout.c: Cleanup

- src/utilities/mbsvplist.c
- Split help_message at new lines
- Combine definition and initialization for ssv_bounds
- status = -> status &= so that errors can propage to the final print
> mbsvplist.c: Cleanup

- src/utilities/mbctdlist.c
- Align help_message with new lines
- Set max string length for sscanf
- Remove status assignment when failure leads to immediate exit
- Add const
- Add TODO for course_old and speed_made_good_old complaints from cpplint
> mbctdlist.c: Cleanup

- src/utilities/mbextractsegy.c
- Set maximum sscanf string size
- Add const
> mbextractsegy.c: Cleanup

- src/utilities/mbpreprocess.c
- Comment out status = that are masked by exit
- Remove unnecessary status =
> mbpreprocess.c: Cleanup

- src/utilities/mbsvpselect.c
- Set max string length on sscanf
- Do not use fflush on stdin
- Comment out unused variable
- Combine adjacent if (verbose == 1) blocks
- Flag some probable incorrect ifs with TODO
> mbsvpselect.c: Cleanup

- src/utilities/mbsegypsd.c
- Initialize variables
- Line up new lines for help_message
- Add const
- Set maximum string length for sscanf of strings
> mbsegypsd.c: Cleanup

- src/utilities/mbprocess.c
- Comment out suspicious setting of corrtableuse->nangle and add TODO
- Add {} for a "for" around an "if {}"
- Add {} for else in if {} else ;
- Localize variables noticed by cppchecker
- Restructure if with ternary if to allow const
- Comment out status = that are masked by exit
- Set maximum string length for sscanf reading of a string
> mbprocess.c: Cleanup

- src/utilities/mbdatalist.c
- Comment out forcing status to be MB_SUCCESS
> mbdatalist.c: Cleanup

- src/utilities/mbgpstide.c
> mbgpstide.c: Cleanup

- src/utilities/mbgrid.c
- Remove unused erfcc
- Remove commented out dead code
- Flag if () a; else a;
- Add const
- Comment out status = that are masked
> mbgrid.c: Cleanup

- src/utilities/mbhistogram.c
- Add const
- Check index bounds before accessing array
> mbhistogram.c: Cleanup

- src/utilities/mbhysweeppreprocess.c
- Add const
- Comment out status = that are masked out exit
- Combine neighboring ifs that are the same
> mbhysweeppreprocess.c: Cleanup

- src/utilities/mbminirovnav.c
- Factor out GetNumRecords()
- Remove the need for nrecord
- Add const
- Comment out the unused interp_status
> mbminirovnav.c: Cleanup

- src/utilities/mbneptune2esf.c
- Remove unused mbclean_save_edit()
- Make funcs void returns that are always success: line_array, print_pings, free_pings
- Remove i from the outer scope around line_array being called
- Add const
- Comment out self assignment of beam
- Do not force status = MB_SUCCESS near the end of main
- Drop i from debugging print of cur_ping
> mbneptune2esf.c: Cleanup

- src/utilities/mbrollbias.c
- Rename one i to i1
- Comment out status = that are are masked by exit
- Print message to stderr when status is MB_FAILURE
> mbrollbias.c: Cleanup

- src/utilities/mbrolltimelag.c
- Comment out unused setup variables
- Combine adjacent if cond that are the same
> mbrolltimelag.c: Cleanup

- src/utilities/mbrphsbias.c
- Comment out status = when maske by exit()
- Comment out unused files_tot
> mbrphsbias.c: Cleanup

- src/utilities/mbsegygrid.c
- const int -> enum
- Comment out debugging prints of variables that are always 0
- Add const
- Use ternary if for setting variables
> mbsegygrid.c: Cleanup

- src/utilities/mbset.c
- Remove unused fstat
- Remove redundant check of AMPSSCORRTOPOFILE
- Print warning if status is MB_FAILURE
> mbset.c: Cleanup

- src/mbio/mbsys_elacmk2.c
- src/mbio/mbsys_gsf.c
- src/mbio/mbsys_hsds.c
- src/mbio/mbsys_hysweep.c
- src/mbio/mbsys_image83p.c
- src/mbio/mbsys_jstar.c
mbsys_elacmk2.c mbsys_gsf.c mbsys_hsds.c mbsys_hysweep.c
mbsys_image83p.c mbsys_jstar.c
> mbio: Comment out unused variables and use (void) to flag unused args

- src/mbio/mbsys_reson7k.c
- interp_status = -> interp_status &=
- Comment out unused settings of interp_status
- Add const
> mbsys_reson7k.c: Cleanup

- src/mbio/mbsys_reson7k3.c
- Add const
- Flag used uninitialized
- interp_status = -> interp_status &=
- Comment out unchecked setting of interp_status
- Add assert for j1 j2 not being set
> mbsys_reson7k3.c: Cleanup

- src/mbio/mbsys_sb.c
- Remove extra comment lines
- Comment out unused vars
- (void) unused args
> mbsys_sb.c: Cleanup

- src/mbio/mbsys_simrad2.c
- localize variables
- add const
- flag bug in xtrackss
> mbsys_simrad2.c: Cleanup

- src/mbio/mbsys_simrad3.c
- Add TODO about probably bug in alloc and for sure bug in zero (#751)
- Add const
> mbsys_simrad3.c: Cleanup

- src/mbio/mbsys_simrad.c
- Take out unused variables
- Add const
> mbsys_simrad.c: Cleanup

- src/utilities/mbset.c
In preparation for src/utilities/*.c going to C++
> mbset.c: explicit -> is_explicit as explicit is a C++ keyword

- src/mbio/mbsys_netcdf.c
CSA run: scan-build-9 make mbsys_netcdf.lo
```
mbsys_netcdf.c:2533:3: warning: Value stored to 'status' is never read
status = mb_freed(verbose, __FILE__, __LINE__, (void **)&store->mbVelProfilTime, error);
^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> mbsys_netcdf.c: status = -> status &= and add check of status

- src/utilities/mbprocess.cc
- Add an constructor with an initializer list for mbprocess_grid_struct
- Remove memset calls on mbprocess_grid_struct
- Remove comparisons with true and false
> mbprocess.cc: Cleanup

- src/mbio/mb_io.h
- test/mbio/Makefile.am
- test/mbio/Makefile.in
- test/mbio/mb_read_init_test.cc
> Introduce test/mbio/mb_read_init_test.cc

- configure
- configure.ac
- libtool
- src/deprecated/mb7kpreprocess.cc
- src/mbio/mb_access.c
- src/mbio/mb_config.h
- src/mbio/mb_config.h.in
- src/mbio/mb_define.h
- src/mbio/mb_io.h
- src/mbio/mbr_em300mba.c
- src/mbio/mbr_em300raw.c
- src/mbio/mbr_em710mba.c
- src/mbio/mbr_em710raw.c
- src/mbio/mbr_kemkmall.c
- src/mbio/mbr_reson7k3.c
- src/mbio/mbr_reson7kr.c
- src/mbio/mbsys_ldeoih.c
- src/mbio/mbsys_ldeoih.h
- src/mbio/mbsys_reson7k.c
- src/mbio/mbsys_reson7k.h
- src/mbio/mbsys_reson7k3.c
- src/mbio/mbsys_reson7k3.h
- src/mbio/mbsys_simrad3.c
- src/utilities/mbbackangle.cc
- src/utilities/mbfilter.cc
- src/utilities/mbgrid.cc
- src/utilities/mbpreprocess.cc
- src/utilities/mbprocess.cc
- test/mbio/Makefile.in
Made mbpreprocess, mbprocess, and the generation of ancilliary files by both to work again for Reson and Kongsberg data.
> Update master to caress-tmp

- test/mbio/mb_read_init_test.cc
> mb_read_init_test.cc: Disable errorFileDoesNotExist

- .gitignore
- ChangeLog.md
- configure
- configure.ac
- configure.cmd
- libtool
- src/mbio/mb_config.h
- src/mbio/mb_read_init.c
- src/mbio/mbr_reson7kr.c
- src/mbio/mbsys_reson7k.c
- src/mbnavadjust/mbnavadjust_prog.c
- src/utilities/mbgrid.cc
- test/mbio/Makefile.in
- test/utilities/mbinfo_test.py
This update has some fixes to mbgrid and the mbr_reson7kr i/o module, plus the versioning for doing a beta release 5.7.6beta22.
> Preparing for 5.7.6beta22

- ChangeLog.md
- configure.cmd
- libtool
- src/utilities/Makefile.am
- src/utilities/Makefile.in
- test/utilities/Makefile.am
- test/utilities/Makefile.in
Tweaks to the build system - Actually turn off building mbsvpselect with proj4
> Trying again to get build to work with proj 4

- src/mbedit/mbedit_prog.c
- Don't use line continuations
- Add const
> mbedit_prog.c: Initial cleanup

- docker/Dockerfile
- docker/README.md
@dwcaress Just an initial PR to start integrating the dockerization of the system.
Right now, this PR just adds a subdirectory `docker` with a Dockerfile and a readme. There're pending aspects to be defined (hopefully soon) but I'd like for us to have a basis moving forward. 
Most immediate aspects to consider include:
- I'm currently setting up the automatic image build and publication upon a push to the master branch.  This uses a mechanism defined on Docker Hub. 
- Publication of the image.  Currently done under the MBARI org at Docker Hub: https://hub.docker.com/r/mbari/mbsystem .
- In general, we need to define the various relevant "spaces." For example, maybe you want the image to be published somewhere else?
> Preparing for dockerization

- src/mbedit/mbedit_bxutils.c
Pull request #842 / bbf4b503af11323b55bebb3669c1f6b7610c0517 was somehow reverted.
> mbedit_bxutils.c: Remove ARGLIST, ARG, GRA, UARG, GRAU

- src/mbedit/mbedit_callbacks.c
- src/mbeditviz/mbeditviz_callbacks.c
- src/mbgrdviz/mbgrdviz_callbacks.c
- src/mbview/mb3dsoundings_callbacks.c
- src/mbview/mbpingedit_callbacks.c
- src/mbview/mbview_callbacks.c
-  mbedit/mbedit_callbacks.c
-  mbeditviz/mbeditviz_callbacks.c
-  mbgrdviz/mbgrdviz_callbacks.c
-  mbview/mb3dsoundings_callbacks.c
-  mbview/mbpingedit_callbacks.c
-  mbview/mbview_callbacks.c
> */*callbacks.c: Remove ARGLIST and related K&R constructs

- src/deprecated/mbauvnavusbl.cc
- src/mbaux/mb_readwritegrd.c
- src/mbedit/mbedit_prog.c
- src/mbgrdviz/mbgrdviz_callbacks.c
- src/mbio/mb_get_all.c
- src/mbio/mb_navint.c
- src/mbio/mb_read_init.c
- src/mbio/mb_write_init.c
- src/mbio/mbr_hsatlraw.c
- src/mbio/mbr_hsldedmb.c
- src/mbio/mbr_hsldeoih.c
- src/mbio/mbr_hsuricen.c
- src/mbio/mbr_hsurivax.c
- src/mbio/mbr_mr1aldeo.c
- src/mbio/mbr_mr1bldeo.c
- src/mbio/mbr_mr1prhig.c
- src/mbio/mbr_sb2100rw.c
- src/mbio/mbr_sbifremr.c
- src/mbnavadjust/mbnavadjust_io.c
- src/mbnavedit/mbnavedit_prog.c
- src/mbvelocitytool/mbvelocity_prog.c
- src/otps/mbotps.c
- src/utilities/mbcopy.cc
- src/utilities/mbfilter.cc
- src/utilities/mbprocess.cc
- src/utilities/mbset.cc
Only needs one NUL.
- "\0" → 0x00 0x00
- "" → 0x00
> Drop the extra \0 in "\0".

- src/mbedit/mbedit_prog.c
-Wsequence-point: may be undefined
Fixes #869
> mbedit_prog.c: Remove double setting of beamflag.

- src/surf/mem_surf.c
- Start formatting the code - the original style is hard to read
- Add const
> mem_surf.c: Cleanup

- src/surf/pb_math.c
> pb_math.c: Cleanup

- src/surf/mem_surf.c
- Fix formatting / remove extra white space
- Localize some variables
- Remove some extra parens
- Some `/* */` -> `//`
> mem_surf.c: Partial cleanup

- src/mbio/mbsys_surf.c
- Add const
- Remove extra parens
> mbsys_surf.c: Simplify mbsys_get_depth()

- src/mbview/mbview_primary.c
- Order includes
- Add const
- int boolean -> bool
- first == true -> first
> mbview_primary.c: Cleanup

- src/mbview/mbview_bxutils.c
- Include stdbool.h
- Error on Xt older than 5
- Directly use mbtowc and drop dombtowc
- Add const
- Remove extra parens
- Remove old CONVERT
- Remove old MENU_POST
- Remove old SET_BACKGROUND_COLOR
> mbview_bxutils.c: Cleanup first third

- src/mbview/mbview_bxutils.c
- Remove unnecessary #if block
- Remove unnecessary prototypes
> mbview_bxutils.c: Cleanup

- src/mbview/mbview_callbacks.c
- Remove unused BxManageCB, BxUnmanageCB, BxExitCB
- static Cardinal ac -> local to functions Cardinal ac
- Add const
- Remove some commented out dead code
- Remove unecessary comments
- Add a scope to localize XColor vars
> mbview_callbacks.c: Cleanup

- src/mbeditviz/mbeditviz_prog.c
- Remove unnecessary variables
- Add const
> mbeditviz_prog.c: Cleanup

- src/README.md
See rethinking structure here: #1020
> src/README.md: Add structure of libs, bin, data/doc, and trn [skip ci]

- src/mbaux/mb_zgrid.c
- Start to localize variables
- Remove some gotos
- Add const
- Initialize jmnew
```
mb_zgrid.c:358:6: warning: ‘jmnew’ may be used uninitialized in this function [-Wmaybe-uninitialized]
358 |  int jmnew;
```
> mb_zgrid.c: Cleanup

- src/mbedit/mbedit_prog.c
> mbedit_prog.c: Cleanup

- src/mbedit/mbedit_bxutils.c
- Remove XTPOINTER define
- Remove doMbstowcs and dombtowc
- Fix initialization of colorsymbols
> mbedit_bxutils.c: Cleanup

- src/mbedit/mbedit.h
> mbedit.h: Have argument names match those in the c file

- ChangeLog.md
- configure.ac
Updated ChangeLog.md for #1064
> Updated ChangeLog.md for #1064

- docker/Dockerfile
- docker/README.md
- docker/user/README.md
- docker/user/mbsystem.sh
Hi @dwcaress 
Please review and merge when you get a chance. Again, only changes under the docker and docker/user dirs.
BTW, I just updated the public-facing page at Docker Hub with the contents of the user/README.md: https://hub.docker.com/r/mbari/mbsystem
Note: I'm also updating the notes and scripts related with the use of network shares, which at the moment I'm only maintaining on our mbscentos7 vm.  In general, if considering this as a rather "special" use case, I could suggest that any overall guidance on that regard be given (on-demand, perhaps) through other channels (mailing lists, wiki page, ...).  I'm just thinking that there might be more involved "network share" use cases than our "titan" case and that we don't actually have ample expertise on these aspects.  Thoughts?
> include needed mesa-dri-drivers, and various doc/script updates

- ChangeLog.md
- src/photo/mbgetphotocorrection.cc
- src/photo/mbphotomosaic.cc
Mbphotomosaic and mbgetphotocorrection: Another iteration trying to bet image
gain and exposure correction to work correctly.
> Mbphotomosaic and mbgetphotocorrection update

- docker/Dockerfile
- docker/centos/scripts/install-proj.sh
Applies to https://github.com/dwcaress/MB-System/issues/807
> Fix problems with the docker build

- ChangeLog.md
- src/macros/Makefile.am
- src/macros/Makefile.in
- src/macros/mbm_trnplot
- src/mbtrnutils/mbtrnpp.c
Mbtrnpp: Improved TRN result logging, including having all log files from a
session placed in the same directory named according to the start time. Also
added automated plotting of the TRN results using a new plot macro
mbm_trnplot.
Mbm_trnplot: New plotting macro that generates two map views of the results from
an mbtrnpp session.
> Improvements to mbtrnpp, including new plot macro mbm_trnplot

- src/mbgrdviz/mbgrdviz_callbacks.c
Mbgrdviz: augmented and corrected the headers of route and site files output by mbgrdviz, better self documenting the formats of these files.
> MBgrdviz improved route and site headers

- src/mbio/mb_format.c
- src/utilities/mbgrid.cc
- src/utilities/mbmosaic.cc
Fixed bug in datalist functions related to use of alternative navigation.
> Fix to datalist functions

- ChangeLog.html
- ChangeLog.md
- src/mbio/mb_define.h
- src/photo/mbphotomosaic.cc
> Fix mbphotomosaic

- ChangeLog.html
- ChangeLog.md
- src/gsf/CMakeLists.txt
- src/mbio/mb_define.h
Fix GSF build, release 5.8.1beta06
> Fix GSF build, release 5.8.1beta06

- ChangeLog.html
- ChangeLog.md
- src/mbio/CMakeLists.txt
- src/mbio/mb_define.h
Set 5.8.1beta7
Removed mb_config.h from installed headers.
> Set 5.8.1beta7
