dwcaress/MB-System

src/gmt/mbswath.c
It's already defined in gmt's gmt_mb.h
=> Don't redefine gmt_get_cpt() macro

src/surf/mb_sapi.h
Let me start a series of PR to bring up my Win branch in sync to master. This one just includes types_win32.h instead of ``<rpc/types.h>``
=> On Win include types_win32.h

src/utilities/mbinfo.c
Excluding the (0,0) from the good_nav is not good enough. I've found many cases with (0.0xxx, 0.0yyy). This PR excludes all inside a square of 0.005 around 0,0
=> Strengthen the ``good_nav`` case. 

src/mbtrn/iowrap-posix.c, src/mbtrn/iowrap-posix.h, src/mbtrn/iowrap.h, src/mbtrn/mbtrn-server.c, src/mbtrn/mlog.c, src/mbtrn/r7kc.c
But there is one more case. I had to replace ``byte buf[x];`` in ``r7kc.c`` because AFAIK that's not valid C code and Visual Studio agrees with me (though apparently both clang and gcc let go). 
There are other cases like this but not in PRs yet.
=> Mostly Win stuff

src/utilities/mbsvpselect.c
Isolated this change in a different PR because it's just more than Win #ifdefs.
VS does not accept ``char original[strlen(fname)];`` and I think correctly because AFAIK C doesn'y allow doing static allocation with a variable size (that's dynamic allocation, no?). Anyway my ignorance or not, VS doesn't accept that. So replaced the code with classic dynamic mem allocation.
=> Change not portable C code

src/mbio/mbsys_kmbes.c
Tested on kmall example data using the following:
`$ mbm_makedatalist -S.kmall -Odatalist.mb-1`
`$ mbdatalist -O -Z -V`
`$ mbotps -I datalist.mb-1 -M -D60.0 -V`
`$ mbsvplist -P -V`
`$ mbprocess`
Mbprocess ran through the kmall examples datalist with no errors for after filling in the svp extract/insert methods. 
Thanks, Ben
=> add extract/insert methods for kmall svp

src/mbio/mbr_kemkmall.c, src/mbio/mbsys_kmbes.h
Hi Dave, 
This commit should take care of the parsing errors we've been seeing. The cause was an erroneous definition of the CHE data format, which led to misalignments in the .mb261 file...  Also did some clean-up in the dbg printouts. 
As I mentioned earlier today, I've found that in some of the example kmall files provided by Kongsberg there's an error in a few of the MRZ datagrams. The malformed packets contained duplicate information that's appended at the tail of the nominal data format (after the seabed image samples). The indexing algorithm successfully filters those packets out.
I'll continue testing as we discussed. 
Thanks!
Ben
=> fix CHE packet parsing and update dbg5 formating

travis/script.sh
This goes with the workaround for macosx failing to detect X11 and PROJ 6: https://github.com/dwcaress/MB-System/commit/e9b12d03d78c21959c2393c0d3a41c4196b87e42
The workaround adds complexity that it would be nice to get rid of.
The eventual solutions are one or more of:
1) Fix the detections of X11 and PROJ >=0 to work with C++
2) Set the language to C only for the tests that require it.
e.g.
```m4
AC_LANG_PUSH([C])
AC_LANG_POP([C])
```
See: https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Language-Choice.html
=> Autoconf cpp testing: Add --enable-test to configure of travis-ci test run

src/mbio/mb_define.h, src/mbio/mbr_hysweep1.c, src/mbio/mbsys_hysweep.c, src/mbio/mbsys_hysweep.h
- Add extern C to mbsys_hysweep.h
- Do some of what include what you use would do:
- Make headers better at standing alone:
Add `#include "mb_define.h"` to mbsys_hysweep.h
- Put `#include "mbsys_hysweep.h"` first
=> Prepare for hydrosweep testing

src/mbio/mb_format.c
- Wrap `ifdef WIN32`
- Switch return to void
- Noticed during #96
- Should it be WIN32 or _WIN32?
Also remove unused file_ok from mb_imagelist_read
Checked with:
cppcheck --enable=all --std=c99 --force mbio/mb_format.c
=> Clean cvt_to_nix_path

src/mbio/mbr_mgd77dat.c, src/mbio/mbr_mgd77tab.c, src/mbio/mbr_mgd77txt.c
Found with:
```bash
cppcheck --enable=all --std=c99 --force mbr_mgd77*.c 2>&1 | grep "'shift'"
```
```
[mbr_mgd77dat.c:871]: (style) Variable 'shift' is assigned a value that is never used.
[mbr_mgd77dat.c:1035]: (style) Variable 'shift' is assigned a value that is never used.
[mbr_mgd77tab.c:2031]: (style) Variable 'shift' is modified but its new value is never used.
[mbr_mgd77txt.c:976]: (style) Variable 'shift' is assigned a value that is never used.
```
Where:
```bash
cppcheck --version
Cppcheck 1.83
```
=> mbr_mgd77: Comment out `shift` increment that is not used.

src/mbio/mb_absorption.c, src/mbio/mb_read_init.c, src/mbio/mbr_3dwisslp.c, src/mbio/mbr_3dwisslr.c, src/mbio/mbr_em300mba.c, src/mbio/mbr_em300raw.c, src/mbio/mbr_kemkmall.c, src/mbio/mbr_reson7k3.c, src/mbio/mbsys_3ddwissl.c, src/mbio/mbsys_kmbes.c
Used:
```bash
cppcheck --enable=style *.c 2>&1 | grep -i unused
```
Skipped mbsys_reson7k3.c as it is under development.  e.g. https://github.com/dwcaress/MB-System/commit/24e7ef8ecdf66a938bb1a13367bb75a727d2c31e
[mbsys_reson7k3.c:51]: (style) Unused variable: i
[mbsys_reson7k3.c:124]: (style) Unused variable: time
[mbsys_reson7k3.c:125]: (style) Unused variable: header
[mbsys_reson7k3.c:126]: (style) Unused variable: ReferencePoint
[mbsys_reson7k3.c:127]: (style) Unused variable: UncalibratedSensorOffset
[mbsys_reson7k3.c:128]: (style) Unused variable: CalibratedSensorOffset
[mbsys_reson7k3.c:129]: (style) Unused variable: Position
<SNIP>
And there are quite a few:
```bash
cppcheck --enable=style mbsys_reson7k3.c 2>&1 | grep -i unused | wc -l
117
```
=> mbio: Remove some of the unused variable warnings

src/mbio/mbr_mgd77dat.c, src/mbio/mbr_mgd77tab.c, src/mbio/mbr_mgd77txt.c
Found with:
```bash
cppcheck --enable=all --std=c99 --force mb*77*.[ch] 2>&1 | grep "'status'"
```
```
[mbr_mgd77dat.c:254] -> [mbr_mgd77dat.c:259]: (style) Variable 'status' is reassigned a value before the old one has been used.
[mbr_mgd77dat.c:259] -> [mbr_mgd77dat.c:260]: (style) Variable 'status' is reassigned a value before the old one has been used.
[mbr_mgd77dat.c:303] -> [mbr_mgd77dat.c:304]: (style) Variable 'status' is reassigned a value before the old one has been used.
<SNIP>
```
There are likely many more occurrences of this issue.
Useful discussion here:
https://stackoverflow.com/questions/2488406/why-doesnt-c-have-or-for-booleans
=> mbr_mgd77: Use `&=` for status so that failures are not hidden.

travis/script.sh
Debugging info in binaries is only going to slow down CI runs.
Looks like this reduces total time for a run by ~10%
=> Drop `-g` from travis builds.

src/mbio/mbr_hsatlraw.c
This uncovered two issues:
- Using status for values other than MB_SUCCESS / MB_FAILURE
- fprintf returns the number of characters printed
- Use a `count` variable rather than `status`
- Hiding possible failures if there are cases where a call may fail,
but a following call succeeded.
- Switch `=` to `&=` for things that return status
- Drop the assignment when it would be lost anyways
```
cppcheck --enable=all --std=c99 --force src/mbio/mbr_hsatlraw.c
Checking src/mbio/mbr_hsatlraw.c ...
[src/mbio/mbr_hsatlraw.c:235] -> [src/mbio/mbr_hsatlraw.c:240]: (style) Variable 'status' is reassigned a value before the old one has been used.
[src/mbio/mbr_hsatlraw.c:240] -> [src/mbio/mbr_hsatlraw.c:241]: (style) Variable 'status' is reassigned a value before the old one has been used. …
```
=> mbr_hsatlraw.c: Fix status reassigned value before old one used.

src/man/man1/mbformat.1, src/utilities/mbformat.c
Also corrects the SYNOPSIS so that it doesn't run into the following `mbformat`.
Fixes #126.
=> Update mbformat.1 man page for -W and mbformat -H for -K and -W.

src/mbio/mb_defaults.c
- Move `HOME` to the outer file scope
- Change prototype for `getenv` to `include <stdlib.h>`
- Add `const` when possible
- Remove redundant assignment of status to `MB_SUCCESS`
=> mb_defaults.c: Cleanup

src/mbio/mb_put_comment.c
- Remove redundant initialization of time_i
- `status =` → `status &=` to catch failures in both mb_insert and mb_write_ping
=> mb_put_comment.c: Cleanup

src/mbio/mb_process.c
Also move status definition to first use and switch second setting to
`&=` to catch errors in initial mb_pr_readpar.
=> mb_pr_update_metadata(): Fix debugging prints of `process` var before set.

src/mbio/mbsys_singlebeam.c
- `#define` -> `const double`
- Use `C0`..`C7` rather than literals in the math expressions
- Add `const`
=> mbsys_singlebeam_pressuredepth: Cleanup

src/mbio/mb_esf.c, src/mbio/mb_rt.c, src/mbio/mbr_3ddepthp.c, src/mbio/mbr_em12ifrm.c, src/mbio/mbr_em710mba.c, src/mbio/mbr_em710raw.c, src/mbio/mbr_hs10jams.c, src/mbio/mbr_hsatlraw.c, src/mbio/mbr_hsunknwn.c, src/mbio/mbr_imagemba.c, src/mbio/mbr_mbldeoih.c, src/mbio/mbr_mgd77tab.c, src/mbio/mbr_mgd77txt.c, src/mbio/mbr_sb2100bi.c, src/mbio/mbr_sbifremr.c, src/mbio/mbr_xtfb1624.c
Allows the compiler to do better type checking and debuggers to see
the symbolic names rather than just literals.
Also removed some unused defines.
=> mbio: `#define`s -> `static const`

src/mbio/mbr_3ddepthp.c, src/mbio/mbr_3dwisslp.c, src/mbio/mbr_3dwisslr.c, src/mbio/mbr_asciixyz.c, src/mbio/mbr_bchrtunb.c
`cppcheck --enable=all --std=c99 --force` on each file with
```
cppcheck --version
Cppcheck 1.83
```
cppcheck is not that smart and misses a lot of opportunities to reduce the scope of local variables.
Also, it is a bummer that it does not notice when const can be added trivially.
=> mbr_3ddepthp.c ... mbr_bchrtunb.c: Fix cppcheck reduce scope suggestions.

src/mbio/mbr_3ddepthp.c
=> Cleanup mbr_3ddepthp.c.

src/mbio/mbr_dsl120pf.c, src/mbio/mbr_dsl120sf.c, src/mbio/mbr_edgjstar.c, src/mbio/mbr_elmk2unb.c, src/mbio/mbr_em12darw.c, src/mbio/mbr_em12ifrm.c, src/mbio/mbr_em300mba.c, src/mbio/mbr_em300raw.c
- Remove checks on status that happen before status can be `MB_FAILURE`
- Some `status =` -> `status &=` for simple cases of alloc and free
=> mbr_dsl120pf.c ... mbr_em300raw.c: Localize status variable.

src/mbio/mb_time.c, src/mbio/mb_write_init.c, src/mbio/mb_write_ping.c, src/mbio/mbsys_navnetcdf.c, src/mbio/mbsys_netcdf.c, src/mbio/mbsys_oic.c, src/mbio/mbsys_reson.c, src/mbio/mbsys_reson7k.c, src/mbio/mbsys_reson7k3.c, src/mbio/mbsys_reson8k.c, src/mbio/mbsys_sb.c, src/mbio/mbsys_sb2000.c, src/mbio/mbsys_sb2100.c, src/mbio/mbsys_simrad.c, src/mbio/mbsys_simrad2.c, src/mbio/mbsys_simrad3.c, src/mbio/mbsys_singlebeam.c, src/mbio/mbsys_stereopair.c, src/mbio/mbsys_surf.c, src/mbio/mbsys_swathplus.c, src/mbio/mbsys_templatesystem.c, src/mbio/mbsys_wassp.c, src/mbio/mbsys_xse.c
- Add `const` when possible
- `status &=` for some of the `status =` overwrite occurrences
=> mb_time.c ... mbsys_xse.c:  Localize status variable.

src/mbedit/mbedit_callbacks.c, src/mbedit/mbedit_prog.c, src/mbio/mb_define.h, src/mbnavadjust/mbnavadjust.c, src/mbnavadjust/mbnavadjust_callbacks.c, src/mbnavadjust/mbnavadjust_prog.c, src/mbnavadjust/mbnavadjust_util.c, src/mbnavedit/mbnavedit_callbacks.c, src/mbnavedit/mbnavedit_prog.c, src/mbnavedit/mbnavedit_util.c, src/mbvelocitytool/mbvelocity.c, src/mbvelocitytool/mbvelocity_callbacks.c, src/mbvelocitytool/mbvelocity_prog.c, src/mbview/mb3dsoundings_callbacks.c, src/mbview/mb_glwdrawa.c, src/mbview/mbpingedit_callbacks.c, src/mbview/mbview_callbacks.c, src/mbview/mbview_nav.c, src/mbview/mbview_pick.c, src/mbview/mbview_plot.c, src/mbview/mbview_primary.c, src/mbview/mbview_process.c, src/mbview/mbview_profile.c, src/mbview/mbview_route.c, src/mbview/mbview_secondary.c, src/mbview/mbview_site.c, src/mbview/mbview_vector.c
Something changed meanwhile and now I have to include WinSock2.h before Windows.h otherwise there are macro conflicts when building with MSVC.
=> Need to include Winsock2.h before windows.h

src/utilities/mbgrid.c
At the moment, if option "-T" is before "-C", and spline tension isn't set as a third parameter to -C, spline tension is reset to the default value (0.0 or 0.35). This PR should fix this bug. The default tension is already set in lines 186-190, so the deleted code was redundant anyway.
It is still slightly odd (open to unexpected behavior?) that tension can be added as an option to -C and overwritten by -T or vice versa, depending on which order they are specified on the command line.
=> Avoid overwriting spline tension in mbgrid if "-T" is before "-C"

src/mbio/mbr_reson7k3.c, src/mbio/mbr_reson7kr.c, src/mbio/mbsys_reson7k.c, src/mbio/mbsys_reson7k3.c
Found with: `egrep '^[[:space:]]+store[[:space:]]*=.*;' *.c`
=> Localize store variable: mbr_reson7k3.c mbr_reson7kr.c mbsys_reson7k.c mbsys_reson7k3.c.

src/mbio/mbsys_reson.c
```bash
cppcheck --enable=all --std=c99 --force -I. -I../mbaux mbsys_reson.c
```
e.g. `[mbsys_reson.c:50]: (style) Variable 'mb_io_ptr' is assigned a value that is never used.`
=> mbsys_reson.c: Remove unused mb_io_ptr.

src/mbio/mbr_mbnetcdf.c
For `MBNETCDF_DEBUG`, just make sure verbose is at least 2.
cppcheck:
```
[mbr_mbnetcdf.c:2903]: (style) Condition 'nc_verbose>=1' is always false
```
=> mbr_mbnetcdf.c: Remove need for nc_verbose

src/utilities/mbformat.c
- Convert `#defines` to `enum MbformatList`
- Make string constants be `static const char[]`
- Add a scope around arg parsing
- Always set format_save to format
=> mbformat.c: Cleanup

src/mbaux/mb_aux.h, src/mbaux/mb_cheb.c
- Add const to some function args
- Remove duplicate function prototypes.  Leave only in the header
- `#undef` a number of PACKAGE_ defs that conflict with GDAL
=> mb_aux.h mb_cheb.c: Cleanup

src/mbaux/Makefile.am
- Remove unused TRN terrain navigation stuff (mbtrn is self contained)
- Change line continuations to `+=`
- Switch `()` to` {}` to be uniform
=> mbaux/Makefile.am: Cleanup

src/bsio/mbbs_io.c
```c
if (sizeof(int) < 4)
return BS_BADARCH;
```
The world is going to come apart if int is less than 4 bytes.
This should be a check at configure time, not runtime.
=> mbbs_io.c: Remove check for sizeof(int) less than 4.

src/bsio/mbbs_tm.c
- Order includes
- Add include of `mbbs.h`
- Define one variable per line
- Move `mbbs_rsttz()` to the top of the file to remove need for a prototype
- Remove prototypes from inside of functions
- Add `const`
- Initialize global pointers to `NULL`
- Remove final `return` from void functions
=> mbbs_tm.c: Cleanup

src/bsio/mbbs_tm.c
Fix mbbs_tm.c - the
#include <stdio.h>
statement was inadvertently deleted.
=> Fix mbbs_tm.c

test/utilities/mbminirovnav_test.py
```
Unable to open projection database at expected location:
/usr/local/inst/share/mbsystem/Projections.dat
Set projection database location using the $MBSYSTEM_HOME and $PROJECTIONS
tags in the install_makefiles script.
```
Change caused by 2985da6e983a20714a718f3db7421d22acc836e8
=> mbminirovnav_test.py: testNoArgs now may throw an exception

src/mbio/mb_define.h
Found with gcc version 8.3 with `-Wall` and  `-Wextra`
=> mb_define.h: Make arg names match for mb_takeoff_to_rollpitch and mb_rollpitch_to_takeoff

src/mbio/mb_buffer.c
- Remove unused mb_io_ptr variables
- `status =` -> `status &=` to catch more errors
=> mb_buffer.c: Cleanup

src/mbio/mb_error.c
cppcheck said:
```
[mb_error.c:207] -> [mb_error.c:202]: (warning) Either the condition 'notice>(63+25+6+1)' is redundant or the array 'notice_msg[95]' is accessed at index 95, which is out of bounds.
[mb_error.c:207] -> [mb_error.c:202]: (warning) Either the condition 'notice>95' is redundant or the array 'notice_msg[95]' is accessed at index 95, which is out of bounds.
```
Also some minor cleanup of redundant comments.
=> mb_error.c: Fix out of bounds read of notice_msg in mb_notice_message.

src/mbio/mb_fileio.c
- Add const
- Remove unused set of buffer_status
- Minor formatting fixes
=> mb_fileio.c: Cleanup

travis/script.sh
I suspect this is adding ~30% to total time for a CI run.  As the code
improves, the amount of additional time for checking should decrease
some.  I suspect that logging all the warnings is current a
substantial load on travis runs.
=> travis/script.sh: Turn off -Wall for now.

src/mbnavadjust/mbnavadjust_callbacks.c, src/mbvelocitytool/mbvelocity_prog.c, src/otps/mbotps.c, src/utilities/mbbackangle.c, src/utilities/mbcopy.c, src/utilities/mbdefaults.c, src/utilities/mbfilter.c, src/utilities/mbgpstide.c, src/utilities/mblevitus.c, src/utilities/mbmosaic.c, src/utilities/mbprocess.c, src/utilities/mbsslayout.c
- getenv should always come from stdlib.h
- ctime should always come from time.h
Using local prototypes of standard functions is risky.
See also:
man 3 getenv
man 3 ctime
http://www.cplusplus.com/reference/cstdlib/getenv/
http://www.cplusplus.com/reference/ctime/
=> Stop including local ctime() getenv() prototypes.

src/utilities/mbdumpesf.c
- Use stdbool
- Add const
- Call exit with code directly
- Increase the size of `esf_header` to prevent a buffer overflow
=> mbdumpesf.c: Cleanup

src/mbio/mb_define.h, src/mbio/mb_get_value.c
When working on mblevitus.c, this blocked me from making `lonptr` and `latptr` const.
=> mb_ddmmss_to_degree(): Make text arg const.

src/utilities/mbsegyinfo.c
- Use stdbool
- Remove unused #defines
- Add const
- Comment out unused code
- Use ternary if to make one line define and set for stream
- Call exit with the error define rather than an error variable
- Sort min/max variables
- Create scopes for getopt and mb_segy_read_init
=> mbsegyinfo.c: Cleanup

src/mbio/mbr_xtfb1624.c, src/mbio/mbr_xtfr8101.c
clang complaints:
```
mbr_xtfb1624.c:1490:21: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
if (time_i[2] < 0 && time_i[2] > 31)
~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
mbr_xtfb1624.c:1488:21: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
if (time_i[1] < 0 && time_i[1] > 12)
~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
mbr_xtfb1624.c:1486:24: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
if (time_i[0] < 1970 && time_i[0] > 2100)
~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
```
=> mbr_xtfb1624.c: Fix tautology in mbr_rt_xtfb1624(() - && → ||

src/utilities/mbclean.c, src/utilities/mbcopy.c, src/utilities/mbctdlist.c, src/utilities/mbswplspreprocess.c, src/utilities/mbvoxelclean.c
mbclean.c mbcopy.c mbctdlist.c mbswplspreprocess.c mbvoxelclean.c
- Add stdbool include for files that use true/false
- grep -l false *.c  | xargs grep -L '#include <stdbool.h>'
=> utilities: Cleanup

src/mbio/mbr_edgjstar.c, src/mbio/mbr_kemkmall.c, src/mbio/mbsys_elacmk2.c, src/mbio/mbsys_gsf.c, src/mbio/mbsys_hdcs.c, src/mbio/mbsys_hs10.c, src/mbio/mbsys_hsds.c, src/mbio/mbsys_hsmd.c, src/mbio/mbsys_hysweep.c, src/mbio/mbsys_image83p.c, src/mbio/mbsys_jstar.c, src/mbio/mbsys_ldeoih.c, src/mbio/mbsys_mr1.c, src/mbio/mbsys_mr1b.c, src/mbio/mbsys_singlebeam.c, src/mbio/mbsys_swathplus.c, src/mbio/mbsys_xse.c
mbr_edgjstar.c mbr_kemkmall.c mbsys_elacmk2.c mbsys_gsf.c mbsys_hdcs.c
mbsys_hs10.c mbsys_hsds.c mbsys_hsmd.c mbsys_hysweep.c
mbsys_image83p.c mbsys_jstar.c mbsys_ldeoih.c mbsys_mr1.c mbsys_mr1b.c
mbsys_singlebeam.c mbsys_swathplus.c mbsys_xse.c
- Localize variables / move "MBIO function <%s> called\n", __func__" debugging print to front of functions
- Remove extra comment lines
- Add const
- Add include of stdbool
=> mbio: misc cleanup

src/utilities/mbrolltimelag.c
- #define -> const int
- exit(error) of a constant -> exit(constant)
- Add a scope around mb_get_format to reduce scope of vars
- Add const
- Add TODO with why mb_reallocd?
=> mbrolltimelag.c: Cleanup

src/utilities/mbinfo.c
Also:
- Switch enum to typedef enum
- int len1, len2 -> size_t
- Add an int tmp to output_format parsing
=> mbinfo.c: Localize variables

src/utilities/mb7k2jstar.c, src/utilities/mbcopy.c
route_file and mfile showed up on debian testing with just -O2 (no -g)
as junk in the debug print messages.
=> mb7k2jstar.c mbcopy.c: Initialize string buffers.

src/utilities/mb7k2ss.c
`-Werror=maybe-uninitialized` thinks that these can possibly be problems.
It's hard to follow the logic to know if there were actual bugs.
Found by `-Wall -Wextra`
=> mb7k2ss.c: Initialize linenumber, rangelast, ss_altitude, range, and ttime_min_use

configure, configure.ac
proj_create exists in proj 5.2.0, but proj_normalize_for_visualization does not.
=> configure.ac: Use proj_normalize_for_visualization to detect proj 6.x.

src/utilities/mbhsdump.c
- Remove redundant comment
- if status is MB_FAILURE at exit, print a warning
=> mbhsdump.c: Cleanup

src/utilities/mbinsreprocess.c
- Comment out unused printfield::formatset
- Add const
- Use ternary if to allow const
- Comment out extra check for mLatK
- status = -> /* status &= */
- Warning if status is MB_FAILURE at the end
=> mbinsreprocess.c: Cleanup

src/utilities/mblist.c
- status = -> /* status &= */ for status that are masked by exit
- Don't set status when setting read_data from mb_datalist_read
- Comment out unused shellstatus
- Add const
=> mblist.c: Cleanup

src/mbio/mbsys_atlas.c, src/mbio/mbsys_benthos.c, src/mbio/mbsys_dsl.c, src/mbio/mbsys_elac.c, src/mbio/mbsys_hsmd.c
mbsys_atlas.c mbsys_benthos.c mbsys_dsl.c mbsys_elac.c mbsys_hsmd.c
=> mbio: Comment out unused vars and use (void) to flag unused args

src/mbio/mbsys_kmbes.c
- Fix indenting
- Add const
- Add assert and fprintf complain for unhandled jnav <= 0
- Initialized some variables and flagged probable bugs
- Comment out unused interp_status
=> mbsys_kmbes.c: Cleanup

src/mbio/mbsys_simrad2.c
- Comment out unused lines
- Comment out unused sets of interp_status
- interp_status = -> interp_status &=
=> mbsys_simrad2.c: Cleanup

src/mbio/mbsys_simrad3.c
=> mbsys_simrad3_zero_ss: Use a different looping variable for inner and outer loops

src/utilities/Makefile.am
In preparation for switching utilities to C++
=> utilities/Makefile.am: Add missing mbminirovnav_SOURCES

src/utilities/mb7kpreprocess.c, src/utilities/mbareaclean.c, src/utilities/mbclean.c, src/utilities/mbfilter.c, src/utilities/mbgrid.c, src/utilities/mbkongsbergpreprocess.c, src/utilities/mbnavlist.c, src/utilities/mbsvpselect.c
- Remove (void*) cast from mb_double_compare in qsort calls
mb_double_compare has the correct signature
- Fix the cast in calling mb_extract_platform()
- C++ doesn't allow writable string literals
- Combine definition and initialization of strings
- Initialize double with a double literal
- Create a scope inside of case to localize variable declaration
- strchr returns a const char *
=> utilities: Cleanup in prep for converting C to C++

src/mbio/mb_buffer.c
Issues found with clang static analyzer (CSA) version 9.
This is my first use of CSA on MB-System, so here is what the command
and warnings look like:
```
scan-build-9 make mb_buffer.lo
mb_buffer.c:492:3: warning: Value stored to 'status' is never read
status = MB_FAILURE;
^        ~~~~~~~~~~
mb_buffer.c:581:3: warning: Value stored to 'status' is never read
status = MB_FAILURE;
^        ~~~~~~~~~~
mb_buffer.c:664:3: warning: 3rd function call argument is an uninitialized value
fprintf(stderr, "dbg2       kind:       %d\n", *kind);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mb_buffer.c:750:3: warning: 3rd function call argument is an uninitialized value
fprintf(stderr, "dbg2       kind:       %d\n", *kind);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> mb_buffer.c: Reenable found checks and set kind to MB_DATA_NONE when there is an error

src/utilities/mbpreprocess.cc
Trying to address most of these:
```
base=mbpreprocess; \rm $base.lo; scan-build-9 make $base.lo && (cppcheck --enable=all --std=c++14 --force --inconclusive -I. -I../mbaux -I../mbio $base.cc)
scan-build: Using '/usr/lib/llvm-9/bin/clang' for static analysis
depbase=`echo mbpreprocess.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../../libtool  --tag=CXX   --mode=compile /usr/share/clang/scan-build-9/bin/../libexec/c++-analyzer -DHAVE_CONFIG_H -I. -I../../src/mbio  -I../../src/mbio -I../../src/mbaux -I../../src/gsf  -I/usr/include/gmt -I/usr/include    -g -O2 -MT mbpreprocess.lo -MD -MP -MF $depbase.Tpo -c -o mbpreprocess.lo mbpreprocess.cc &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  /usr/share/clang/scan-build-9/bin/../libexec/c++-analyzer -DHAVE_CONFIG_H -I. …
```
=> mbpreprocess.cc: Cleanup

src/mbio/mb_io.h, src/mbtrnutils/mbtrnpp.c
Based on include-what-you-use (IWYU), mb_io.h should not have anything
from mbtrn.  Of all the mbtrn includes in mb_io.h, only merror.h was
needed in mbtrnpp.c.
Found while trying to add a test for mb_read_init() in #795
=> Move merror.h include from mb_io.h to mbtrnpp.c.

src/mbio/mb_time.c, test/mbio/mb_time_test.cc
It is certainly possible to catch more invalid times than this and it
will flag leap seconds as bad.  This will prevent a buffer overflow of yday.
It's not clear what the time input is supposed to be.  Is it UTC, UT1, GPS,
or other?
- https://www.nist.gov/pml/time-and-frequency-division/nist-time-frequently-asked-questions-- faq
http://leapsecond.com/java/gpsclock.htm
Fixes #794
=> mb_time.c: Basic range check of the time_i inputs to mb_get_time.

src/mbio/mb_time.c
- Fix typo of missing space at the end of a sentence
- Localize status var a bit
Skipped some of the changes I recommended in #795. Of note:
- Using local variables like year rather than time_i[0]
- Just directly warning and returning when a time is bad
- Making separate functions to print time_i and time_j
=> mb_time.c: Minor cleanup

src/mbio/mb_define.h, src/mbio/mb_proj.c, src/utilities/mbsvpselect.cc
Build failed on Centos 7 w/ proj 4.8 due to lack of proj header file geodesic.h.
The proposed fix is to isolate the geod_*() calls into mb_proj.c and use the existing #ifdef structure there to handle using proj 4 or 6. The new mb_geod_*() functions have been added to mb_proj.c, mb_define.h and arc now called by mbsvpselect.
=> Trying to fix build problem for mbsvpselect between proj4 and proj6

src/utilities/mbinfo.cc
mbinfo.cc is failing for me on Ubuntu 16.04 LTS with gcc 5.4.0: 
> mbinfo.cc: In function ‘int main(int, char**)’:
> mbinfo.cc:2159:24: error: ‘isnan’ was not declared in this scope
>          if (isnan(sigma))
>                         ^
> mbinfo.cc:2159:24: note: suggested alternative:
> In file included from /usr/include/c++/5/random:38:0,
>                  from /usr/include/c++/5/bits/stl_algo.h:66,
>                  from /usr/include/c++/5/algorithm:62,
>                  from mbinfo.cc:36:
> /usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
>      isnan(_Tp __x)
This build failure seems to have been introduced in 98b32be410 and I think what's going on is summarized in https://stackoverflow.com/a/39133379 where `<algorithm>` is pulling in `<cmath>` which undefines isnan in …
=> Switched to std::isnan in mbinfo

src/deprecated/mbstripnan.cc
Based on issue found in PR #830 building on centos.
Why the old version is working, it's best to go ahead
and make the code correct since it's simple fix.
Converted the C headers to C++, removed the windows hack,
and converted exit(0) to EXIT_SUCCESS.
=> mbstripnan.cc: isnan -> std::isnan and minor cleanup

src/mbedit/mbedit_bxutils.c, src/mbio/mb_esf.c, src/mbnavadjust/mbnavadjust_util.c, src/mbnavedit/mbnavedit_util.c, src/mbvelocitytool/mbvelocity_bxutils.c, src/mbview/mb3dsoundings_bxutils.c, src/mbview/mb_glwdrawa.c, src/mbview/mbpingedit_bxutils.c, src/mbview/mbview_bxutils.c
There is no need to harass the compiler these days with register.
The optimizer can do a pretty good job of handling what should or should
not be in a register. If any registers are really needed, the need to
have a comment next to them explaining why.
=> Stop using register on parameters and variables.

ChangeLog.md, configure, configure.ac, libtool, src/mbio/mb_config.h, src/mbio/mb_proj.c
Going back to approach in which MB-System starts using the Proj 6 API when the function proj_normalize_for_visualization() is available, which started with Proj release 6.1.0. If proj_normalize_for_visualization() is not available, MB-System will use the deprecated Proj 4 API. This effectively bypasses the API changes made for Proj releases 5.0 through 6.0.
=> Prepping for release 5.7.6beta24

src/utilities/mbctdlist.cc, test/utilities/mbconfig_test.py
Two minor fixes to pass unit tests I'm seeing fail on ubuntu bionic and xenial
mbctdlist.cc was printing illegal UTF-8 characters due to an uninitialized character array which caused it's unit test to fail.  Simply initialized the first element to '\0' in this case, but could use memset to set the whole array if wanted.
mbconfig_test.py:  subscriptable 'Match' objects were introduced in python 3.6 and xenial ships with 3.5.  Switched to the longer form but equivalent '.group()' method to get at the matching text in the test
=> Minor fixes to pass tests on Ubuntu Bionic/Xenial

src/surf/util_surf.h
- Remove extra whitespace
- Simplify enum typedefs
- Normalize include guard
- Remove duplicate function prototypes
- Drop unneccessary extern
=> util_surf.h: Cleanup

.travis.yml
This change will limit docker builds to only travis jobs initiated `dwcaress/MB-System`.  Without it any fork can modify the docker image files and run travis to overwrite what's on hub.docker.com
=> Only dwcaress/MB-System can trigger docker image builds.

src/mbgrdviz/mbgrdviz_callbacks.c
- Order includes
- Don't use a long to store EXIT_FAILURE
- Add const
=> mbgrdviz_callbacks.c: Partial cleanup

src/mbio/mbsys_reson7k.c
28 -> 6 to match the size of reserved.
Fixes #941
=> mbsys_reson7k.c: Fix buffer overflow in s7kr_calibratedsnippet initialization

src/mbview/mbpingedit_callbacks.c
- Comment out BxFindTopShell prototype
- Remove commented out acs variable
=> mbpingedit_callbacks.c: Cleanup

.travis.yml
See #974 for description of the failure
=> Disable osx travis build as gmt-config not found (#974).

src/mbview/mbview_bxutils.c
- /* */ -> // for tighter code
- Remove IGNORE_CONVERT
- Remove LFUNC
- Convert LFUNC prototypes to normal C
- Reorder functions to remove the need for most prototypes
- Combine definition and initialization of local variables
=> mbview_bxutils.c: Cleanup

src/mbaux/mb_cheb.c
mb_cheb.c:1306:3: warning: ‘bnorm’ may be used uninitialized in this function [-Wmaybe-uninitialized]
1306 |   fprintf(nout,
=> mb_cheb.c: Initialize bnorm and rnorm in mblsqr_lsqr

src/mbaux/mb_aux.h, src/mbaux/mb_readwritegrd.c, src/mbaux/mb_truecont.c, src/mbaux/mb_xgraphics.c, src/mbaux/mb_zgrid.c
- Remove trailing whitespace
- Remove extra comment lines
- Initialize variables that triggered `-Wmaybe-uninitialized`
- Set the proper structure for initializing `XRectangle[]`
=> mbaux: Cleanup

src/mbedit/mbedit_prog.c
- getopt.h included as <>
- Use an unsigned code for printf of unsigned variable
- Remove redundant settings of *nbuffer
- if (bool expr) {} else if (!bool expr) {} <- Comment out the second if
and have only else
- Add TODO for places that an || might need to be switched to &&
- Remove pointer castings for qsort.  No need to cast a pointer to void *
=> mbedit_prog.c: Cleanup

src/mbedit/mbedit_creation.c
- Move font defines to after includes
- Remove unused prototypes for BX_SINGEL, XPM_PIXMAP, and BX_SET_BACKGROUND_COLOR
- Remove redundant cast to XmString for tmp0 in XMStringFree calls
=> mbedit_creation.c: Cleanup

ChangeLog.md, configure, configure.ac, libtool, src/mbio/mb_config.h, src/mbio/mb_format.c, src/mbio/mbr_oicgeoda.c, src/utilities/mbpreprocess.cc
Formats MBF_OICGEODA (141) and MBF_OICMBARI (142): Fixed support for old OIC
format DSL120 interferometric sonar data. Processing of these data now works
with mbpreprocess and mbprocess again. The sidescan data were compromised
by treating unsigned amplitude values as signed, and treating null samples as
valid.
=> Fix format MBF_OICGEODA (141) and MBF_OICMBARI (142)

src/utilities/Makefile.am, src/utilities/Makefile.in
The build was failing at src/utilities/mbsvpselect.cc due to a failure to file geodesic.h. This was fixed by adding libproj_CPPFLAGS to AM_CPPFLAGS in src/utilities/Makefile.am, and then resconstruct the build system.
=> Fixed build problem with change to src/utilities/Makefile.am

.dockerignore, docker/README.md, docker/user/README.md, docker/user/mbsystem.sh
Here's an initial launcher script intended to facilitate running the dockerized programs, plus some user oriented instructions (all preliminary and of course subject to be moved to wherever this would make more sense once there's a more final version of the the docker image).
Along with this I started doing GUI tests on a CentOS 7 and will later on do some similar tests on a Windows 10 VM (that I just requested IS to create).
=> initial notes for usage of dockerized MB-System and launcher script

ChangeLog.md, configure, configure.ac, src/mbio/mb_config.h, src/mbnavadjust/mbnavadjust_prog.c
Mbnavadjust: Changed handling of fixed surveys when updating the project grid
or applying the solution. Previously the files of fixed surveys were ignored,
even if they previously had been adjusted before being set to fixed. Now, the
unchanged *.na0 file will be output and the navadjust state will be updated
so that mbprocess will apply the unchanged navigation.
=> Change handling of fixed files in mbnavadjust

ChangeLog.md, ci/travis/build_linux/script.sh, libtool, src/mbaux/mb_readwritegrd.c, src/mbnavadjust/mbnavadjust_prog.c, test/utilities/Makefile.in
Mbnavadjust: Fixed crash on Linux when executing the Auto Set Vertical Offset
function (didn't dimension arrays large enough).
Writing GMT grids: Fixed crash reported by Joaquim Luis on Windows when writing
GMT grids - the problem was a function call that caused GDAL to allocate a string
but then it allowing that pointer to be freed in GMT functions. The solution is
to copy the string and free the pointer using a GDAL call.
=> Fixes mbnavadjust crash and crash on Windows writing GMT grids

ChangeLog.md, src/utilities/mblevitus.cc
Mblevitus: Fixed errors that had been inadvertently created as part of commit #448. Thanks to Joaquim Luis for finding and fixing this.
=> Mblevitus fix

configure, configure.ac, libtool
I added the line
prefix=$ac_default_prefix
near the top of configure.ac in order to insure the installation prefix is embedded into mbio/mb_config.h to be accessed by mbconfig. This appears to have the effect of overriding the default prefix for Homebrew installations, which makes the install phase fail because Homebrew installations go into /usr/local/Cellar/package/ not directly into /usr/local.
=> Change configure.ac to fix problem with Homebrew installation

.travis.yml, docker/centos/scripts/install-gmt.sh, docker/centos/scripts/install-proj.sh, docker/ubuntu/Dockerfile, docker/ubuntu/scripts/install-gmt.sh, docker/ubuntu/scripts/install-proj.sh
Fixes an issue in Ubuntu Xenial where GMT libraries could not be found at run time which failed some unit tests.
=> Update ld cache in docker images when install GMT or GDAL from source

src/html/mbsystem_formats.html, src/htmlsrc/mbsystem_formats.html, src/man/man3/mbio.3, src/mbio/mbr_em710mba.c
Several places in the documentation, format 59 (EM710 processing format) was incorrectly described as the vendor format (same as format 58). This has been corrected, and "Simrad" has been updated to "Kongsberg" in the mbio man page for consistency with the rest of the code.
=> Fix documentation for format 59 - MBF_EM710MBA

src/man/man1/mbgrd2obj.1
Adding correct shared library (mbsystem.so) to use on a linux system build.
=> Update mbgrd2obj.1 with shared library to use on a linux system

ChangeLog.md, src/mbio/mbr_reson7k3.c, src/mbio/mbr_reson7kr.c, src/mbio/mbsys_reson7k.c, src/mbio/mbsys_reson7k3.c
Formats 88 (MBF_RESON7KR) and 89 (MBF_RESON7K3): Fixed bug in handling of
PingMotion data records (7012) that caused memory overruns and seg faults.
=> Bug fix for formats 88 and 89

docker/Dockerfile
This adds 3 lines to Dockerfile that allows including the image in a [docker-compose.yml](https://github.com/mbari-org/SeafloorMappingDB/blob/main/debug.yml) like this:
```
mb-system:
image: mb-system
container_name: mb-system
volumes:
- /Users/mccann/.ssh:/root/.ssh:z
command: /usr/sbin/sshd -D
```
Then we can run MB-System commands from our django container, e.g.:
```
(base) ➜  SeafloorMappingDB git:(main) ✗ docker-compose run --rm django /bin/bash
Creating seafloormappingdb_django_run ... done
PostgreSQL is available
root@5a22e05fa9b4:/app# ssh root@mb-system mbinfo -h
Program MBINFO
MB-system Version 5.7.9beta16
MBINFO reads a swath sonar data file and outputs
some basic statistics.  If pings are averaged (pings > 2)
MBINFO estimates the variance for each of the swath
beams by reading …
```
=> Add openssh-server and RUN commands to allow ssh connections

docker/Dockerfile
Without this setting in /root/gmt.conf:
```
GMT_CUSTOM_LIBS = /usr/local/lib/mbsystem.so
```
We get this error message:
```
[root@cc1c218cc7cd ~]# gmt mbgrd2obj
ERROR: No module named mbgrd2obj was found.  This could mean one of four cases:
1. There actually is no such module; please check your spelling.
2. You used a modern mode module name while running in GMT classic mode.
3. Module exists in the GMT supplemental library, but the library could not be found.
4. Module exists in a GMT custom library, but none was specified via GMT_CUSTOM_LIBS.
Shared libraries must be in standard system paths or set via environmental parameter LD_LIBRARY_PATH.
```
=> Put GMT_CUSTOM_LIBS in /root/gmt.conf for execution of MB-System gmt modules

src/utilities/mbprocess.cc
This seems to be required to compile on some platforms. Maybe due to compiler version differences? I haven't checked too closely. 
Without this patch, on Fedora 36 with gcc 12.01, I get the following error:
```
mbprocess.cc:5429:37: error: ‘min’ is not a member of ‘std’; did you mean ‘sin’?
5429 |               mask_bounds[2] = std::min(mask_bounds[2], sslat);
|                                     ^~~
|                                     sin
mbprocess.cc:5430:37: error: ‘max’ is not a member of ‘std’; did you mean ‘fmax’?
5430 |               mask_bounds[3] = std::max(mask_bounds[3], sslat);
|                                     ^~~
|                                     fmax
make[3]: *** [Makefile:962: mbprocess.o] Error 1
```
=> add missing include in mbprocess.cc

.gitignore, ChangeLog.md, configure, configure.ac, src/mbio/mb_config.h, src/mbtrnutils/Makefile.am, src/mbtrnutils/Makefile.in, src/mbtrnutils/mbgrd2octree.cc, src/mbtrnutils/mbgrdtilemaker.cc, src/mbtrnutils/mbtrnpp.c
Mbtrnpp: Added options to set the TRN search area on the command line and in
cfg files. Fixed wrapper script mbtrnpp.sh so that the number of cycles
to be used is set correction.
Mbm_trnplot: Fixed plotting macro to work with the current mbtrnpp output.
Mbgrd2octree: Recast program that translates a topography grid in a projected
coordinate system (like UTM) into a TRN octree model. This program now used
MB-System-like arguments, e.g. mbgrd2octree --input=grid --output=octree
Mbgrdtilemaker: Added new program to generate a tileset of octrees for TRN from a
reference grid in a projected coordinate system (like UTM). This tileset can be
used by mbtrnpp.
=> Update for 5.7.9beta35

src/mbio/mbsys_reson7k.c
A recent change from `int` -> `unsigned int` causes the computation of `ssacrosstrack[i]` to wraparound. The change was made in [this commit](https://github.com/dwcaress/MB-System/commit/996a4ecdac09af702f06b137ec1cccd5a0301b29).
The bug shows up as extremely large bounds when running `mbinfo` on an mb88 dataset, since `ssacrosstrack[i]` eventually is used to compute lat/long for the sidescan pixel.
For example, running
```
mbinfo -I ~/mb88_problems/20091021_162557_ventresca7125.s7k.s7k.mb88
```
prior to this change outputs
```
Limits:
Minimum Longitude:    -121.858863263   Maximum Longitude:    6026.381436848
Minimum Latitude:    -1450.970669383   Maximum Latitude:      489.421090170
```
and after this change outputs
```
Limits:
Minimum Longitude:    -121.858929958   Maximum Longitude: …
```
=> Fix unsigned wraparound

BuildAndInstall.md, CMakeLists.txt, ChangeLog.md, src/mbio/mb_define.h, src/mbnavadjust/mbnavadjust_callbacks.c, src/mbnavadjust/mbnavadjust_io.c, src/mbnavadjust/mbnavadjust_io.h, src/mbnavadjust/mbnavadjust_prog.c, src/mbnavadjust/mbnavadjustmerge.c, src/mbtrnutils/mbtrnpp.c, src/utilities/mbinfo.cc, src/utilities/mblist.cc, test/mbio/CMakeLists.txt
Mbinfo and mblist: Fixed bug introduced with the alternate navigation capability that caused mbinfo and mblist to fail when running on single files rather than through datalists.
Mbnavadjust: Improved handling of reference grids. The list of reference grids now starts with an option "<Previously Selected Reference Grid>" that will cause loading a section with a global tie set to also load the reference grid (if any) loaded when the tie was created. If a specific reference grid is selected from the reference grid list, then that reference grid will be loaded when any section is loaded, regardless of whether a prior global tie already exists.
Mbtrnpp: Fixed bug identified by Kent Headley that caused divide by zeros when calculating swath width filtering of soundings.
CMake build system: …
=> Fixes to mbnavadjust, mbinfo, mblist, mbtrnpp, CMake build system

ChangeLog.md, src/mbnavadjust/mbnavadjustmerge.c, src/mbtrnutils/mbtrnpp.c
Mbnavadjustmerge: Added options to shift global ties singly or all together.
Mbtrnpp: Fixed use of covariances from TRN: to get x y z covariances use covariance[2], covariance[0], covariance[5] rather than 0, 1, and 2.
=> mbnavadjustmerge and mbtrnpp

ChangeLog.md, src/macros/mbm_grdplot, src/mbaux/mb_track.c, src/mbio/mb_define.h, src/mbio/mbsys_image83p.c, src/mbio/mbsys_image83p.h, src/utilities/mbauvloglist.cc, src/utilities/mbbackangle.cc, src/utilities/mbprocess.cc, src/utilities/mbsslayout.cc
Format 192 (MBR_IMAGEMBA): Fixed correction of beam amplitude values (previously corrected values were not successfully inserted into the data structure).
Mbauvloglist: Program altered so that time and utcTime fields are printed by default in format %17.6f and %12.6f, respectively, even though the MBARI Dorado AUV log files have default formats of %8.8e instead. Now by default the timestamps are printed usefully with precision to microseconds.
Mbbackangle: Fixed bug in which mbbackangle did not process sidescan or amplitude data from files in formats that support variable numbers of beams and pixels.
Mbsslayout: Fixed bug in which a command to swap the starboard and port sidescan channels was ignored.
=> Fixes for 5.7.9beta69

ChangeLog.md, src/mbio/mb_define.h, src/otps/CMakeLists.txt, src/utilities/CMakeLists.txt, src/utilities/mbconfig.cc, src/utilities/mblevitus.cc
Make build system: Fixed creating the levitus.h header file used by mblevitus and mbconfig to define the location of the Levitus database and the OTPS installation, thereby making mblevitus and mbconfig work properly.
=> Cmake build system fix

src/mbio/mb_process.c, src/mbnavadjust/mbnavadjust_io.c, src/mbview/mbview_pick.c
Addressed possible array overflow warnings in
src/mbio/mb_process.c
src/mbnavadjust/mbnavadjust_io.c
src/mbview/mbview_pick.c
by changing sprintf() calls to snprintf() with the write length limited to the size of the target array.
=> Addressed possible array overflow warnings

ChangeLog.md, src/mbio/mb_define.h, src/mbio/mb_read_init.c, src/photo/mbphotomosaic.cc
Mbphotomosaic: Added options to detect and correct dark images (for when strobe lights partially drop out), to ignore dark images, and to allow image prioritization on the basis of camera heading.
=> Mbphotomosaic

ChangeLog.html, ChangeLog.md, src/mbaux/mb_truecont.c, src/mbio/mb_define.h, src/mbio/mbr_em710raw.c, src/mbio/mbr_sbsioswb.c, src/mbio/mbsys_sb.c, src/mbio/mbsys_simrad3.c, src/mbio/mbsys_simrad3.h, src/utilities/mbgrid.cc, src/utilities/mbpreprocess.cc
Format 16 (MBF_SBSIOSWB): Fixed bug that became evident when processing old Scripps SeaBeam Classic data in format 16 on a MacOs Sonoma machine. This turned out to be a poorly formed preprocessor macro for rounding floating point values in code dating from 1992.
Formats 58 (MBF_EM710RAW) and 59 (MBF_EM710MBA):  Fixed bug in which some bathymetry edits were applied to the wrong pings. Third generation Kongsberg multibeams produce two cross profiles with each ping cycle, but represent these as two separate pings with the same ping time. MB-System distinguishes between pings using the timestamps rather than ping numbers (because not all sonars produce ping numbers), so pings with the same timestamp confuse the beam flag handling code. The solution is to add a small amount of time to the …
=> Fix support for formats MBF_SBSIOSWB and MBF_EM710RAW

ChangeLog.md, docker/README.md, src/man/man1/mbpreprocess.1, src/mbio/mb_define.h, src/utilities/mbextractsegy.cc, src/utilities/mbpreprocess.cc
MBextractsegy: changed calculation of section plot bounds to more consistently catch the seafloor arrival within the plot.
MBpreprocess: fixed initialization of the --kluge-fix-7k-times option.
Docker image: updated documentation in the Docker directory.
=> Updated Docker documenation + minor fixes

CMakeLists.txt
Added a message that displays OTPS installation directory. Can be changed using -DotpsDir=PATH when running cmake.
=> Display OTPS installation directory

ChangeLog.md, src/mbaux/mb_delaun.c, src/mbaux/mb_truecont.c, src/mbio/mb_define.h, src/mbnavadjust/mbnavadjust_io.c, src/mbnavadjust/mbnavadjustmerge.c
Mbnavadjustmerge: Fixed (again, this time hopefully for real) the --reimport-all-files option so that large projects can be reimported with a single command. Added a --reimport-survey option.
=> Mbnavadjustmerge reimport function

src/mbtrnav/CMakeLists.txt, src/mbtrnav/build-utils/FindLibPROJ.cmake, src/mbtrnav/build-utils/FindNetCDF.cmake, src/mbtrnav/cmake/Libtrnav.cmake.in, src/mbtrnav/newmat/bandmat.cpp, src/mbtrnav/opt/Makefile, src/mbtrnav/opt/rov/Makefile, src/mbtrnav/opt/sentry/README-trndev-build.md, src/mbtrnav/opt/sentry/trndev-build-cmake.sh, src/mbtrnav/opt/sentry/trndev-build-gnu.sh, src/mbtrnav/qnx-utils/DataLogReader.cc, src/mbtrnav/qnx-utils/TimeP.cc, src/mbtrnav/terrain-nav/TNavPointMassFilter.cpp, src/mbtrnav/trnw/Makefile, src/mbtrnutils/mbtrnpp.c
sync with build file changes in libtrnav.
This primarily involves gnu make and sentry cmake/gnu make build scripts to fix issues (e.g. opt/rov linkage errors under linux) and integrate opt/rov (trnxpp) target at the top level.
Suppress gctp warnings (geolib build target only); the warnings are for future deprecation in the open C2X standard.
Until it is deprecated (becomes and error), it makes sense to disable the warning for that target, rather than do extensive modification to gctp source.
Also fixes (not suppresses) warnings in mbtrnav/qnx-utils (DataLogReader,TimeP) and mbtrnutils (mbtrnpp).
Excludes files used by MB-System build.
Tested on macOS Sonoma 14.7 and Ubuntu 22.04 LTS.
=> sync with build changes in libtrnav

src/mbio/mb_fileio.c, src/mbtrn/utils/frames7k.c, src/mbtrnutils/mbtrnpp.c
This change set addresses two issues related to mbtrnpp shutdown (e.g. by SIGINT):
- Using socket input for MB1 format, when SIGINT is raised (via CTRL-C), mbtrnpp would not exit. In that context, mbtrnpp would have to be backgrounded and killed manually to stop it. 
The mb1r input methods were not setting the return values needed to indicate that mb_get_all should exit. Logic is needed in mbtrnpp and mb_fileio; similar logic is used for other mbtrnpp real-time input types. Even with this fix, once mbtrnpp has connected to the MB1 input source, it will continue to pend until the MB1 input socket has closed; once it does, mbtrnpp will exit cleanly. This is due to a blocking read in the MB1 reader (mb1r). For now, I'd recommend we keep the blocking read, which is what we'd want during …
=> Bugfix: mbtrnpp shutdown

src/mbtrn/tools/mbtrnpp-plot/qp-trnu.conf.sh, src/mbtrnutils/mbtrnpp.c
Add convergence info (converged, valid) fields to trn_mse_dat and trn_mle_dat CSV log messages in trnu log.
In mbtrnpp-plot, Use convergence info in plots comparing MMSE and MLE position estimates to navigation (pose) data.
This will not work with logs that don't have the convergence data.
The plot configuration file (qp-trnu.conf.sh) includes the original code and annotations to use it instead if needed.
Example attached
[conv-plot-example.pdf](https://github.com/user-attachments/files/20630945/conv-plot-example.pdf)
=> Trndev: add converge info to position estimate vs nav plots

src/mbgrd2gltf/CMakeLists.txt, src/mbgrd2gltf/model.cpp
This is in response to reported problems building on Ubuntu 22:
```
[ 71%] Linking CXX executable mbgrd2gltf
/usr/bin/ld: CMakeFiles/mbgrd2gltf.dir/model.cpp.o: in function
`mbgrd2gltf::model::dracoEncodeGeometry(std::vector<float,
std::allocator<float> > const&, std::vector<unsigned int,
std::allocator<unsigned int> > const&, mbgrd2gltf::Options const&,
std::vector<unsigned char, std::allocator<unsigned char> >&)':
model.cpp:(.text+0x2d5b9): undefined reference to
`draco::GeometryAttribute::Init(draco::GeometryAttribute::Type,
draco::DataBuffer*, unsigned char, draco::DataType, bool, long, long)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/mbgrd2gltf/CMakeFiles/mbgrd2gltf.dir/build.make:187: src/
mbgrd2gltf/mbgrd2gltf] Error 1
make[1]: *** [CMakeFiles/Makefile2:3111: …
```
=> Fix src/mbgrd2gltf/CMakeLists.txt to force use of local Draco source files.
